// Launches only the packaged artifact with an isolated, disposable user-data directory.
const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {spawn}=require('node:child_process');const assert=require('node:assert/strict');
async function smoke(artifact){const state=await fs.mkdtemp(path.join(os.tmpdir(),'travel-package-smoke-'));const executable=process.platform==='darwin'?path.join(artifact,'Contents/MacOS/Electron'):path.join(artifact,'Travel Planner.exe');const env={...process.env,TRAVEL_PLANNER_STATE_DIR:state,TRAVEL_PLANNER_BACKGROUND:'1'};delete env.ELECTRON_RUN_AS_NODE;let child,connection,exit;let errors='';
try{
child=spawn(executable,['--remote-debugging-port=0','--user-data-dir='+state],{env,stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>{errors=(errors+b.toString()).slice(-12000);});child.stderr.on('data',b=>{errors=(errors+b.toString()).slice(-12000);});child.on('exit',(code,signal)=>{exit={code,signal};});let port;
for(let i=0;i<600;i++){if(exit)throw Error('PACKAGED_APP_EXITED: '+JSON.stringify(exit)+' '+errors.slice(-2000));try{port=Number((await fs.readFile(path.join(state,'DevToolsActivePort'),'utf8')).split('\n')[0]);}catch{}const debug=/DevTools listening on ws:\/\/127\.0\.0\.1:(\d+)/.exec(errors);port ||= Number(debug?.[1]);if(port)break;await new Promise(r=>setTimeout(r,100));}assert.ok(port,'Packaged app must expose debugging port: '+errors.slice(-1500));let page;
for(let i=0;i<100;i++){const targets=await (await fetch('http://127.0.0.1:'+port+'/json')).json();page=targets.find(t=>t.type==='page'&&t.url.startsWith('travel-app://'));if(page)break;await new Promise(r=>setTimeout(r,100));}assert.ok(page,'Packaged app must load trusted UI');connection=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{connection.addEventListener('open',resolve,{once:true});connection.addEventListener('error',reject,{once:true});});let id=0;
function evaluate(expression){return new Promise((resolve,reject)=>{const requestId=++id;const timer=setTimeout(()=>reject(Error('CDP_TIMEOUT')),5000);const onMessage=event=>{const m=JSON.parse(event.data);if(m.id!==requestId)return;connection.removeEventListener('message',onMessage);clearTimeout(timer);if(m.error||m.result?.exceptionDetails)reject(Error('CDP_EVALUATE_FAILED '+JSON.stringify(m.error||m.result.exceptionDetails)));else resolve(m.result?.result?.value);};connection.addEventListener('message',onMessage);connection.send(JSON.stringify({id:requestId,method:'Runtime.evaluate',params:{expression,returnByValue:true,awaitPromise:true}}));});}
for(let i=0;i<50;i++){if(await evaluate('document.readyState === "complete" && !!document.querySelector("#message")'))break;await new Promise(r=>setTimeout(r,100));}
// 主畫面或第一次使用的引導要等 App 檢查完本機工具才畫出來；慢的機器（例如 Intel Mac 的 CI）要多等一下。
const shown='["Travel Planner","旅程","準備"].some(w=>document.body.innerText.slice(0,200).includes(w))';
for(let i=0;i<150;i++){if(await evaluate(shown))break;await new Promise(r=>setTimeout(r,100));}
const report=await evaluate('({title:document.title,hasComposer:!!document.querySelector("#message"),hasBridge:typeof window.travelDesktop!=="undefined",text:document.body.innerText.slice(0,200)})');assert.ok(report.title);assert.ok(report.hasComposer);assert.ok(report.hasBridge);assert.ok(report.text.includes('Travel Planner')||report.text.includes('旅程')||report.text.includes('準備'),'packaged App shows neither the workbench nor the first-run onboarding: '+JSON.stringify(report.text));return {launched:true,title:report.title,isolatedState:true,platform:process.platform};
}finally{connection?.close();if(child&&!exit){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),new Promise(r=>setTimeout(r,3000))]);if(!exit)child.kill('SIGKILL');}await fs.rm(state,{recursive:true,force:true});}}
module.exports={smoke};if(require.main===module){const artifact=process.argv[2]||path.resolve(__dirname,'../../../.local/distribution/Travel Planner.app');smoke(artifact).then(r=>process.stdout.write(JSON.stringify(r)+'\n')).catch(e=>{process.stderr.write(e.message+'\n');process.exitCode=1;});}
