const fs=require('node:fs/promises');
const {constants}=require('node:fs');
const path=require('node:path');
const {createHash,randomUUID}=require('node:crypto');
const dns=require('node:dns/promises');
const net=require('node:net');
const http=require('node:http');
const https=require('node:https');
const {TextDecoder}=require('node:util');
const MAX_FILE=8*1024*1024,MAX_TEXT=1024*1024,MAX_URL=2*1024*1024,MAX_COUNT=30;
const fail=code=>Object.assign(new Error(code),{code});
const same=(a,b)=>a.dev===b.dev&&a.ino===b.ino;
const regular=s=>s.isFile()&&!s.isSymbolicLink()&&s.nlink===1;
const decode=b=>{try{const text=new TextDecoder('utf-8',{fatal:true}).decode(b);if(/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(text))throw fail('BINARY_TEXT');return text;}catch{throw fail('INVALID_TEXT');}};
async function safeRead(file,max){const stat=await fs.lstat(file);if(!regular(stat)||stat.size>max)throw fail('UNSAFE_ATTACHMENT');const h=await fs.open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{if(!same(stat,await h.stat()))throw fail('UNSAFE_ATTACHMENT');const b=Buffer.alloc(stat.size+1);const {bytesRead}=await h.read(b,0,b.length,0);const after=await h.stat();if(bytesRead!==stat.size||!regular(after)||!same(stat,after)||after.size!==stat.size||after.mtimeMs!==stat.mtimeMs)throw fail('UNSAFE_ATTACHMENT');return b.subarray(0,bytesRead);}finally{await h.close();}}
function imageInfo(b,ext){
  let width,height,mime;
  if(ext==='.png'&&b.length>=33&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))&&b.toString('ascii',12,16)==='IHDR'){width=b.readUInt32BE(16);height=b.readUInt32BE(20);mime='image/png';}
  else if(['.jpg','.jpeg'].includes(ext)&&b.length>4&&b[0]===255&&b[1]===216){let pos=2;while(pos+4<=b.length){if(b[pos++]!==255)break;let marker=b[pos++];while(marker===255&&pos<b.length)marker=b[pos++];if(marker===0xda||marker===0xd9)break;if(marker>=0xd0&&marker<=0xd7)continue;const length=b.readUInt16BE(pos);if(length<2||pos+length>b.length)break;if([0xc0,0xc1,0xc2].includes(marker)&&length>=8){height=b.readUInt16BE(pos+3);width=b.readUInt16BE(pos+5);mime='image/jpeg';break;}pos+=length;}}
  else if(ext==='.webp'&&b.length>=30&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP'){
    const kind=b.toString('ascii',12,16);if(kind==='VP8X'){width=1+b.readUIntLE(24,3);height=1+b.readUIntLE(27,3);}else if(kind==='VP8 '&&b[23]===0x9d&&b[24]===1&&b[25]===0x2a){width=b.readUInt16LE(26)&0x3fff;height=b.readUInt16LE(28)&0x3fff;}else if(kind==='VP8L'&&b[20]===0x2f){const bits=b.readUInt32LE(21);width=(bits&0x3fff)+1;height=((bits>>>14)&0x3fff)+1;}mime='image/webp';
  }
  if(!mime||!width||!height||width>8192||height>8192||width*height>20000000)throw fail('INVALID_IMAGE');return {mime,width,height};
}
function publicIPv4(address){if(net.isIP(address)!==4)return false;const [a,b,c]=address.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===168||b===0||b===2))||(a===198&&(b===18||b===19||(b===51&&c===100)))||(a===203&&b===0&&c===113));}
function safeURL(raw){let url;try{url=new URL(raw);}catch{throw fail('UNSAFE_REFERENCE_URL');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password||(url.port&&!['80','443'].includes(url.port))||url.href.length>4000)throw fail('UNSAFE_REFERENCE_URL');const host=url.hostname.toLowerCase().replace(/\.$/,'');if(host==='localhost'||host.endsWith('.localhost')||host.endsWith('.local')||host.endsWith('.internal')||host.includes(':')||(net.isIP(host)&&!publicIPv4(host)))throw fail('UNSAFE_REFERENCE_URL');url.hash='';return url;}
function requestPublic(url,{address,signal,maxBytes}){return new Promise((resolve,reject)=>{const req=(url.protocol==='https:'?https:http).get(url,{agent:false,signal,headers:{Accept:'text/html, text/plain, application/json','Accept-Encoding':'identity','User-Agent':'TravelPlanner/1.0 (reference reader)'},lookup:(_host,options,callback)=>callback(null,options.all?[{address,family:4}]:address,4)},res=>{const chunks=[];let count=0;res.on('data',chunk=>{count+=chunk.length;if(count>maxBytes){res.destroy(fail('REFERENCE_TOO_LARGE'));return;}chunks.push(chunk);});res.on('error',reject);res.on('end',()=>resolve({statusCode:res.statusCode,headers:res.headers,body:Buffer.concat(chunks)}));});req.on('error',reject);});}
function htmlText(text){return text.replace(/<!--[\s\S]*?-->/g,' ').replace(/<(script|style|noscript|svg|iframe)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(_m,v)=>{if(v[0]==='#'){const n=v[1].toLowerCase()==='x'?parseInt(v.slice(2),16):Number(v.slice(1));return n>0&&n<=0x10ffff?String.fromCodePoint(n):' ';}return {amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '}[v.toLowerCase()];}).replace(/\s+/g,' ').trim();}
async function fetchPublicReference(raw,{resolve=host=>dns.resolve4(host),request=requestPublic,timeoutMs=15000}={}){
  let url=safeURL(raw);const controller=new AbortController();let timeout;const work=(async()=>{for(let i=0;i<=4;i++){
    const addresses=net.isIP(url.hostname)?[url.hostname]:await resolve(url.hostname);const ips=addresses.map(v=>typeof v==='string'?v:v.address);if(!ips.length||ips.some(ip=>!publicIPv4(ip)))throw fail('UNSAFE_REFERENCE_ADDRESS');if(controller.signal.aborted)throw fail('REFERENCE_TIMEOUT');
    const response=await request(url,{address:ips[0],signal:controller.signal,maxBytes:MAX_URL});if(!Buffer.isBuffer(response.body)||response.body.length>MAX_URL)throw fail('REFERENCE_TOO_LARGE');
    if([301,302,303,307,308].includes(response.statusCode)){if(i===4||typeof response.headers.location!=='string')throw fail('REFERENCE_REDIRECT');url=safeURL(new URL(response.headers.location,url).href);continue;}
    if(response.statusCode!==200)throw fail('REFERENCE_HTTP_ERROR');const mime=String(response.headers['content-type']||'').split(';')[0].trim().toLowerCase();if(!['text/html','text/plain','application/json'].includes(mime))throw fail('UNSUPPORTED_REFERENCE_TYPE');if(response.headers['content-encoding']&&!['identity'].includes(response.headers['content-encoding']))throw fail('UNSUPPORTED_REFERENCE_ENCODING');const text=mime==='text/html'?htmlText(decode(response.body)):decode(response.body);if(!text)throw fail('EMPTY_REFERENCE');return {kind:'reference',url:url.href,checkedAt:new Date().toISOString(),text:text.slice(0,60000),truncated:text.length>60000};
  }})();
  try{return await Promise.race([work,new Promise((_,reject)=>{timeout=setTimeout(()=>{controller.abort();reject(fail('REFERENCE_TIMEOUT'));},Math.max(1,Math.min(timeoutMs,30000)));})]);}finally{clearTimeout(timeout);controller.abort();}
}
class AttachmentStore{
  constructor(userData){if(!path.isAbsolute(userData))throw fail('UNSAFE_ATTACHMENT');this.directory=path.join(userData,'attachments');this.anchors=new Map();this.queue=Promise.resolve();}
  scope(target){if(!target||!path.isAbsolute(target.root)||!/^[a-zA-Z0-9_-]{1,100}$/.test(target.slug)||typeof target.accountKey!=='string'||!target.accountKey||target.accountKey.length>300)throw fail('INVALID_ATTACHMENT_TARGET');return path.join(this.directory,createHash('sha256').update(JSON.stringify([target.root,target.slug,target.accountKey])).digest('hex'));}
  async anchor(dir){const stat=await fs.lstat(dir);if(!stat.isDirectory()||stat.isSymbolicLink())throw fail('UNSAFE_ATTACHMENT');const canonical=await fs.realpath(dir);const old=this.anchors.get(dir);if(old&&(!same(old.stat,stat)||old.canonical!==canonical))throw fail('UNSAFE_ATTACHMENT');if(!same(stat,await fs.lstat(dir)))throw fail('UNSAFE_ATTACHMENT');this.anchors.set(dir,{stat,canonical});}
  async ready(target,create=false){const dir=this.scope(target);for(const p of [path.dirname(this.directory),this.directory,dir]){try{await this.anchor(p);}catch(e){if(e.code!=='ENOENT'||!create||this.anchors.has(p))throw e;await fs.mkdir(p,{mode:0o700});await this.anchor(p);}}return dir;}
  run(fn){const p=this.queue.then(fn);this.queue=p.catch(()=>{});return p;}
  async list(target){let dir;try{dir=await this.ready(target);}catch(e){if(e.code==='ENOENT')return [];throw e;}const result=[];for(const name of await fs.readdir(dir)){if(!/^[0-9a-f-]{36}\.json$/.test(name))continue;const item=await this.meta(target,name.slice(0,-5));result.push(item);}return result.sort((a,b)=>a.addedAt.localeCompare(b.addedAt));}
  async meta(target,id){if(typeof id!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(id))throw fail('INVALID_ATTACHMENT_ID');const dir=await this.ready(target);const m=JSON.parse(await safeRead(path.join(dir,id+'.json'),10000));await this.ready(target);if(m.id!==id||!['text','image','reference'].includes(m.kind)||typeof m.name!=='string'||!Number.isSafeInteger(m.size)||m.size<0||m.size>MAX_FILE||typeof m.sha256!=='string'||!/^[a-f0-9]{64}$/.test(m.sha256))throw fail('INVALID_ATTACHMENT');return m;}
  add(target,file){return this.run(async()=>{if(typeof file!=='string'||!path.isAbsolute(file))throw fail('UNSAFE_ATTACHMENT');const ext=path.extname(file).toLowerCase();if(!['.txt','.md','.json','.png','.jpg','.jpeg','.webp'].includes(ext))throw fail('UNSUPPORTED_ATTACHMENT_TYPE');const bytes=await safeRead(file,['.txt','.md','.json'].includes(ext)?MAX_TEXT:MAX_FILE);const image=['.png','.jpg','.jpeg','.webp'].includes(ext);const metadata={kind:image?'image':'text',name:path.basename(file).slice(0,200),...(image?imageInfo(bytes,ext):{mime:ext==='.json'?'application/json':'text/plain'})};if(!image)decode(bytes);return this.write(target,bytes,metadata);});}
  fetchURL(target,url,options){return this.run(async()=>{const reference=await fetchPublicReference(url,options);const bytes=Buffer.from(reference.text);return this.write(target,bytes,{kind:'reference',mime:'text/plain',name:new URL(reference.url).hostname,url:reference.url,checkedAt:reference.checkedAt,truncated:reference.truncated});});}
  async write(target,bytes,metadata){const dir=await this.ready(target,true);if((await this.list(target)).length>=MAX_COUNT)throw fail('ATTACHMENT_LIMIT');const id=randomUUID();const result={id,...metadata,size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),addedAt:new Date().toISOString()};const content=path.join(dir,id+'.bin');await fs.writeFile(content,bytes,{flag:'wx',mode:0o600});try{await this.ready(target);await fs.writeFile(path.join(dir,id+'.json'),JSON.stringify(result)+'\n',{flag:'wx',mode:0o600});return result;}catch(e){try{await this.ready(target);await fs.unlink(content);}catch{}throw e;}}
  async read(target,id){const m=await this.meta(target,id);const dir=await this.ready(target);const bytes=await safeRead(path.join(dir,id+'.bin'),MAX_FILE);await this.ready(target);if(bytes.length!==m.size||createHash('sha256').update(bytes).digest('hex')!==m.sha256)throw fail('ATTACHMENT_CHANGED');return {...m,...(m.kind==='image'?{imagePath:path.join(dir,id+'.bin')}:{text:decode(bytes)})};}
  remove(target,id){return this.run(async()=>{await this.read(target,id);const dir=await this.ready(target);await fs.unlink(path.join(dir,id+'.json'));await this.ready(target);await fs.unlink(path.join(dir,id+'.bin'));return true;});}
}
module.exports={AttachmentStore,fetchPublicReference};
