const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const https=require('node:https');
const path=require('node:path');
const runDefault=promisify(execFile);
const APP_VERSION=require('../package.json').version;
const PINNED_CODEX_VERSION='0.155.1';
const PINNED_CLAUDE_VERSION='2.1.278',PINNED_GEMINI_VERSION='0.46.0';
const RELEASE_API='https://api.github.com/repos/wangch15/travel-planner/releases?per_page=30';
const RELEASE_PREFIX='https://github.com/wangch15/travel-planner/releases/';
const SETUP_URLS=Object.freeze({node:'https://nodejs.org/en/download',codex:'https://developers.openai.com/codex/cli/',claude:'https://code.claude.com/docs/en/setup',gemini:'https://geminicli.com/docs/get-started/installation/',git:'https://git-scm.com/downloads',gh:'https://cli.github.com/',wrangler:'https://developers.cloudflare.com/workers/wrangler/install-and-update/'});
const fail=code=>Object.assign(new Error(code),{code});
function version(v){const m=/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.exec(v);if(!m||m.slice(1).some(n=>!Number.isSafeInteger(Number(n))))throw fail('INVALID_RELEASE_VERSION');return m.slice(1).map(Number);}
function newer(a,b){const aa=version(a),bb=version(b);for(let i=0;i<3;i++){if(aa[i]!==bb[i])return aa[i]>bb[i];}return false;}
async function inspectEnvironment({run=runDefault,platform=process.platform}={}){
  const commands=[{id:'node',cmd:platform==='win32'?'node.exe':'node',args:['--version'],pattern:/^v(\d+\.\d+\.\d+)/,minimumMajor:20},{id:'codex',cmd:process.env.TRAVEL_PLANNER_CODEX_PATH||(platform==='win32'?'codex.exe':'codex'),args:['--version'],pattern:/^codex-cli (\d+\.\d+\.\d+)$/,requiredVersion:PINNED_CODEX_VERSION},{id:'claude',cmd:platform==='win32'?'claude.exe':'claude',args:['--version'],pattern:/(\d+\.\d+\.\d+)/,requiredVersion:PINNED_CLAUDE_VERSION},{id:'gemini',cmd:platform==='win32'?'gemini.cmd':'gemini',args:['--version'],pattern:/(\d+\.\d+\.\d+)/,requiredVersion:PINNED_GEMINI_VERSION},{id:'git',cmd:'git',args:['--version'],pattern:/^git version (\d+\.\d+\.\d+)/},{id:'gh',cmd:platform==='win32'?'gh.exe':'gh',args:['--version'],pattern:/^gh version (\d+\.\d+\.\d+)/},{id:'wrangler',cmd:process.execPath,args:[path.resolve(__dirname,'../../../node_modules/wrangler/wrangler-dist/cli.js'),'--version'],env:{...process.env,ELECTRON_RUN_AS_NODE:'1',WRANGLER_SEND_METRICS:'false'},pattern:/(?:^|\n)(\d+\.\d+\.\d+)(?:\s|$)/}];
  const tools=await Promise.all(commands.map(async item=>{try{const output=await run(item.cmd,item.args,{timeout:8000,maxBuffer:8192,windowsHide:true,...(item.env?{env:item.env}:{})});const match=item.pattern.exec(output.stdout.trim());return {id:item.id,source:item.id==='wrangler'?'bundled':'system',action:item.id==='wrangler'?'connect-cloudflare':item.id==='gh'?'connect-github':'install',status:!match?'unsupported':item.minimumMajor&&Number(match[1].split('.')[0])<item.minimumMajor?'unsupported':item.requiredVersion&&match[1]!==item.requiredVersion?'unsupported':'ready',version:match?.[1]||null,requiredVersion:item.requiredVersion||null,setupUrl:SETUP_URLS[item.id]};}catch{return {id:item.id,source:item.id==='wrangler'?'bundled':'system',action:item.id==='wrangler'?'connect-cloudflare':item.id==='gh'?'connect-github':'install',status:'missing',version:null,requiredVersion:item.requiredVersion||null,setupUrl:SETUP_URLS[item.id]};}}));return {appVersion:APP_VERSION,pinnedCodexVersion:PINNED_CODEX_VERSION,platform,tools};
}
function fetchReleaseDefault({signal}={}){return new Promise((resolve,reject)=>{const req=https.get(RELEASE_API,{signal,headers:{Accept:'application/vnd.github+json','User-Agent':'TravelPlanner-Desktop','X-GitHub-Api-Version':'2022-11-28'},timeout:10000},res=>{if(res.statusCode===404){res.resume();resolve({status:404});return;}const chunks=[];let bytes=0;res.on('data',chunk=>{bytes+=chunk.length;if(bytes>1024*1024){res.destroy(fail('RELEASE_RESPONSE_TOO_LARGE'));return;}chunks.push(chunk);});res.on('error',reject);res.on('end',()=>{try{resolve({status:res.statusCode,data:JSON.parse(Buffer.concat(chunks).toString('utf8'))});}catch{reject(fail('INVALID_RELEASE_RESPONSE'));}});});req.on('timeout',()=>req.destroy(fail('RELEASE_TIMEOUT')));req.on('error',reject);});}
function officialURL(raw,prefix){let u;try{u=new URL(raw);}catch{throw fail('INVALID_RELEASE_URL');}if(u.protocol!=='https:'||u.username||u.password||u.port||u.search||u.hash||!u.href.startsWith(prefix))throw fail('INVALID_RELEASE_URL');return u.href;}
async function checkForUpdates({currentVersion=APP_VERSION,fetchRelease=fetchReleaseDefault,timeoutMs=10000}={}){
  version(currentVersion);const controller=new AbortController();let timer;let response;try{response=await Promise.race([fetchRelease({signal:controller.signal}),new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(fail('RELEASE_TIMEOUT'));},Math.max(1,Math.min(timeoutMs,30000)));})]);}finally{clearTimeout(timer);controller.abort();}if(response.status===404)return {state:'unpublished',currentVersion,assets:[]};if(response.status!==200)throw fail('RELEASE_CHECK_FAILED');
  const entries=Array.isArray(response.data)?response.data:[response.data];const candidates=entries.filter(r=>r&&!r.draft&&!r.prerelease&&typeof r.tag_name==='string'&&r.tag_name.startsWith('desktop-v'));
  if(!candidates.length)return {state:'unpublished',currentVersion,assets:[]};
  candidates.sort((a,b)=>newer(a.tag_name.slice(9),b.tag_name.slice(9))?-1:1);const release=candidates[0],releaseVersion=release.tag_name.slice(9);version(releaseVersion);
  const url=officialURL(release.html_url,RELEASE_PREFIX+'tag/'+release.tag_name);if(new URL(url).pathname!=='/wangch15/travel-planner/releases/tag/'+release.tag_name)throw fail('INVALID_RELEASE_URL');
  if(!Array.isArray(release.assets)||release.assets.length>100)throw fail('INVALID_RELEASE_RESPONSE');const assets=release.assets.map(a=>{if(!a||typeof a.name!=='string'||!/^[\w .()-]{1,180}\.(zip|dmg|exe|msi|yml|yaml|json|sha256|blockmap)$/.test(a.name)||!Number.isSafeInteger(a.size)||a.size<0)throw fail('INVALID_RELEASE_ASSET');const downloadURL=officialURL(a.browser_download_url,RELEASE_PREFIX+'download/'+release.tag_name+'/');if(decodeURIComponent(new URL(downloadURL).pathname.split('/').at(-1))!==a.name)throw fail('INVALID_RELEASE_ASSET');return {name:a.name,url:downloadURL,size:a.size};});
  return {state:newer(releaseVersion,currentVersion)?'available':'current',currentVersion,version:releaseVersion,url,assets};
}
module.exports={inspectEnvironment,checkForUpdates,SETUP_URLS,APP_VERSION,PINNED_CODEX_VERSION};
