const fs=require('node:fs/promises');
const {constants}=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const https=require('node:https');
const {execFile,spawn}=require('node:child_process');
const {promisify}=require('node:util');
const {createHash,randomUUID}=require('node:crypto');
const runDefault=promisify(execFile);
const GEMINI_VERSION='0.46.0',WRANGLER_VERSION='4.135.0';
const SOURCES=Object.freeze({gh:'https://github.com/cli/cli#installation',git:'https://git-scm.com/downloads',node:'https://nodejs.org/en/download',codex:'https://developers.openai.com/codex/cli/',claude:'https://code.claude.com/docs/en/setup',gemini:'https://geminicli.com/docs/get-started/installation/',wrangler:'https://developers.cloudflare.com/workers/wrangler/install-and-update/'});
const LABELS={gh:'GitHub CLI',git:'Git',node:'Node.js',codex:'Codex',claude:'Claude Code',gemini:'Gemini CLI',wrangler:'Cloudflare Wrangler'};
const fail=code=>Object.assign(new Error(code),{code});
const same=(a,b)=>a.dev===b.dev&&a.ino===b.ino;
const digest=b=>createHash('sha256').update(b).digest('hex');
const sh=s=>"'"+s.replaceAll("'","'\\''")+"'";
const ps=s=>"'"+s.replaceAll("'","''")+"'";
const exists=async file=>{try{return (await fs.stat(file)).isFile();}catch{return false;}};
function tool(id){if(!Object.hasOwn(LABELS,id))throw fail('INVALID_TOOL');return id;}
async function readSafe(file,max=65536){const s=await fs.lstat(file);if(!s.isFile()||s.isSymbolicLink()||s.nlink!==1||s.size>max)throw fail('UNSAFE_TOOL_FILE');const h=await fs.open(file,constants.O_RDONLY|constants.O_NOFOLLOW);try{if(!same(s,await h.stat()))throw fail('UNSAFE_TOOL_FILE');const b=Buffer.alloc(s.size+1);const {bytesRead}=await h.read(b,0,b.length,0);const after=await h.stat();if(bytesRead!==s.size||after.size!==s.size||after.mtimeMs!==s.mtimeMs||!same(s,after))throw fail('UNSAFE_TOOL_FILE');return b.subarray(0,bytesRead);}finally{await h.close();}}
function safeDownloadURL(raw){let u;try{u=new URL(raw);}catch{throw fail('UNTRUSTED_TOOL_DOWNLOAD');}if(u.protocol!=='https:'||u.username||u.password||u.port||!['api.github.com','github.com','release-assets.githubusercontent.com','objects.githubusercontent.com','nodejs.org'].includes(u.hostname))throw fail('UNTRUSTED_TOOL_DOWNLOAD');return u;}
async function downloadDefault(raw,{maxBytes=64*1024*1024,timeoutMs=120000}={}){
  const controller=new AbortController();let timer;const task=(async()=>{let url=safeDownloadURL(raw);for(let n=0;n<6;n++){const result=await new Promise((resolve,reject)=>{const req=https.get(url,{signal:controller.signal,headers:{'User-Agent':'TravelPlanner-ToolSetup',Accept:'application/octet-stream'}},res=>{if([301,302,303,307,308].includes(res.statusCode)){res.resume();resolve({redirect:res.headers.location});return;}if(res.statusCode!==200){res.resume();reject(fail('TOOL_DOWNLOAD_FAILED'));return;}const chunks=[];let length=0;res.on('data',b=>{length+=b.length;if(length>maxBytes){res.destroy(fail('TOOL_DOWNLOAD_TOO_LARGE'));return;}chunks.push(b);});res.on('error',reject);res.on('end',()=>resolve({bytes:Buffer.concat(chunks)}));});req.on('error',reject);});if(result.bytes)return result.bytes;if(typeof result.redirect!=='string')throw fail('TOOL_DOWNLOAD_FAILED');url=safeDownloadURL(new URL(result.redirect,url).href);}throw fail('TOOL_DOWNLOAD_REDIRECT');})();
  try{return await Promise.race([task,new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(fail('TOOL_DOWNLOAD_TIMEOUT'));},timeoutMs);})]);}finally{clearTimeout(timer);controller.abort();}
}
async function extractDefault(archive,destination,{platform=process.platform,run=runDefault,maxEntries=5000}={}){
  const command=platform==='win32'?'tar.exe':'/usr/bin/tar';const listed=await run(command,['-tf',archive],{timeout:15000,maxBuffer:1024*1024,windowsHide:true});const entries=listed.stdout.split(/\r?\n/).filter(Boolean);if(!entries.length||entries.length>maxEntries||entries.some(n=>n.startsWith('/')||n.includes('\\')||n.includes(':')||n.split('/').includes('..')||n.includes('\0')))throw fail('UNSAFE_TOOL_ARCHIVE');await run(command,['-xf',archive,'-C',destination],{timeout:60000,maxBuffer:16384,windowsHide:true});
}
async function launchTerminalDefault({platform,scriptPath,script,env}){
  if(platform==='darwin'){await runDefault('/usr/bin/open',['-a','Terminal',scriptPath],{env,timeout:10000,maxBuffer:4096});return;}
  if(platform==='win32'){const command=path.join(env.SystemRoot||'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe');await new Promise((resolve,reject)=>{const child=spawn(command,['-NoProfile','-NoExit','-Command',script],{env,detached:true,stdio:'ignore',windowsHide:false});child.once('error',reject);child.once('spawn',()=>{child.unref();resolve();});});return;}throw fail('UNSUPPORTED_TOOL_PLATFORM');
}
function cleanEnvironment(env){return Object.fromEntries(Object.entries(env).filter(([key])=>!/^(NODE_OPTIONS|NODE_PATH|ELECTRON_RUN_AS_NODE|DYLD_.*|LD_.*|BASH_ENV|ENV)$/.test(key)));}
class ToolSupport{
  constructor(userData,{platform=process.platform,arch=process.arch,home=os.homedir(),env=process.env,run=runDefault,download=downloadDefault,extract=extractDefault,openTerminal=launchTerminalDefault,onProgress=()=>{},now=()=>Date.now()}={}){if(!path.isAbsolute(userData))throw fail('UNSAFE_TOOL_DIRECTORY');Object.assign(this,{userData,platform,arch,home,env,run,download,extract,openTerminal,onProgress,now});this.directory=path.join(userData,'tools');this.plans=new Map();this.anchors=new Map();this.busy=false;}
  emit(tool,state,message){try{this.onProgress({tool,state,message});}catch{}}
  async anchor(dir){const stat=await fs.lstat(dir);if(!stat.isDirectory()||stat.isSymbolicLink())throw fail('UNSAFE_TOOL_DIRECTORY');const canonical=await fs.realpath(dir),previous=this.anchors.get(dir);if(previous&&(!same(previous.stat,stat)||canonical!==previous.canonical))throw fail('UNSAFE_TOOL_DIRECTORY');if(!same(stat,await fs.lstat(dir)))throw fail('UNSAFE_TOOL_DIRECTORY');this.anchors.set(dir,{stat,canonical});}
  async directoryFor(segments=[],create=false){const dirs=[this.userData,this.directory];for(const s of segments){if(typeof s!=='string'||!s||s==='.'||s==='..'||/[\\/\0]/.test(s))throw fail('UNSAFE_TOOL_DIRECTORY');dirs.push(path.join(dirs.at(-1),s));}for(const d of dirs){try{await this.anchor(d);}catch(e){if(!create||e.code!=='ENOENT'||this.anchors.has(d))throw e;if(d===this.userData)await fs.mkdir(d,{recursive:true,mode:0o700});else await fs.mkdir(d,{mode:0o700});await this.anchor(d);}}return dirs.at(-1);}
  async conventionalDirectories(){const delimiter=this.platform==='win32'?';':':';const configured=String(this.env.PATH||this.env.Path||'').split(delimiter);let candidates;if(this.platform==='darwin')candidates=[path.join(this.directory,'npm/node_modules/.bin'),path.join(this.home,'.local/bin'),'/opt/homebrew/opt/node@24/bin','/usr/local/opt/node@24/bin','/opt/homebrew/bin','/usr/local/bin',...configured,'/usr/bin','/bin'];else if(this.platform==='win32')candidates=[path.join(this.directory,'npm/node_modules/.bin'),path.join(this.home,'.local/bin'),this.env.APPDATA&&path.join(this.env.APPDATA,'npm'),this.env.ProgramFiles&&path.join(this.env.ProgramFiles,'nodejs'),this.env.ProgramFiles&&path.join(this.env.ProgramFiles,'Git/cmd'),this.env.LOCALAPPDATA&&path.join(this.env.LOCALAPPDATA,'Programs/Git/cmd'),...configured];else candidates=configured;
    const result=[];for(const dir of candidates.filter(Boolean)){if(!path.isAbsolute(dir)||result.includes(dir))continue;try{if((await fs.stat(dir)).isDirectory())result.push(dir);}catch{}}return result;
  }
  // Official Node.js in the App's tool folder: no Homebrew, admin password or Xcode tools.
  async managedNode(){try{await this.directoryFor(['node']);const state=JSON.parse(await readSafe(path.join(this.directory,'node/current.json')));if(!/^\d+\.\d+\.\d+$/.test(state.version)||state.platform!==this.platform||state.arch!==this.arch||!/^\w{64}$/.test(state.binarySha256))throw fail('INVALID_TOOL_STATE');const dir=await this.directoryFor(['node',state.version+'-'+this.platform+'-'+this.arch]);const bin=this.platform==='win32'?dir:path.join(dir,'bin');const node=path.join(bin,this.platform==='win32'?'node.exe':'node');if(digest(await readSafe(node,256*1024*1024))!==state.binarySha256)throw fail('TOOL_BINARY_CHANGED');return {dir,bin,node,npmCli:path.join(dir,this.platform==='win32'?'node_modules/npm/bin/npm-cli.js':'lib/node_modules/npm/bin/npm-cli.js'),version:state.version};}catch(e){if(e.code==='ENOENT')return null;throw e;}}
  async systemNode(env){const dirs=String(env.PATH||'').split(this.platform==='win32'?';':':');const node=await this.locate(this.platform==='win32'?'node.exe':'node',dirs);if(!node||node.startsWith(this.directory+path.sep))return null;
    try{const out=await this.run(node,['--version'],{timeout:8000,maxBuffer:4096,windowsHide:true,env});if(!(Number(/^v(\d+)\./.exec(String(out.stdout||'').trim())?.[1])>=20))return null;}catch{return null;}
    const dir=path.dirname(node),candidates=this.platform==='win32'?[path.join(dir,'node_modules/npm/bin/npm-cli.js')]:[path.join(dir,'../lib/node_modules/npm/bin/npm-cli.js')];
    if(this.platform!=='win32')try{const npm=await fs.realpath(path.join(dir,'npm'));if(npm.endsWith('npm-cli.js'))candidates.unshift(npm);}catch{}
    for(const cli of candidates)if(await exists(cli))return {node,bin:dir,npmCli:path.resolve(cli)};return null;}
  async downloadNode(){
    const arch=this.arch==='arm64'?'arm64':'x64',suffix=this.platform==='win32'?'win-'+arch+'.zip':'darwin-'+arch+'.tar.gz';
    this.emit('node','downloading','正在從 nodejs.org 下載官方 Node.js。');
    const sums=await this.download('https://nodejs.org/dist/latest-v24.x/SHASUMS256.txt',{maxBytes:65536,timeoutMs:15000});
    if(!Buffer.isBuffer(sums)||sums.length>65536)throw fail('INVALID_TOOL_CHECKSUM');
    const line=sums.toString('utf8').split(/\r?\n/).map(l=>l.trim().split(/\s+/)).find(([,name])=>typeof name==='string'&&name.startsWith('node-v')&&name.endsWith('-'+suffix)&&/^node-v\d+\.\d+\.\d+-/.test(name));
    if(!line||!/^[0-9a-f]{64}$/i.test(line[0]))throw fail('INVALID_TOOL_CHECKSUM');
    const [sha256,name]=line,version=/^node-v(\d+\.\d+\.\d+)-/.exec(name)[1];
    const bytes=await this.download('https://nodejs.org/dist/v'+version+'/'+name,{maxBytes:96*1024*1024,timeoutMs:900000});
    if(!Buffer.isBuffer(bytes)||digest(bytes)!==sha256.toLowerCase())throw fail('TOOL_CHECKSUM_MISMATCH');
    const root=await this.directoryFor(['node'],true),stage=path.join(root,'.stage-'+randomUUID());await fs.mkdir(stage,{mode:0o700});
    try{const archive=path.join(stage,name),expanded=path.join(stage,'expanded');await fs.writeFile(archive,bytes,{flag:'wx',mode:0o600});await fs.mkdir(expanded,{mode:0o700});
      this.emit('node','verifying','檢查碼相符，正在解壓縮 Node.js。');
      await this.extract(archive,expanded,{platform:this.platform,run:this.run,maxEntries:40000});
      const base=path.join(expanded,name.replace(/\.(tar\.gz|zip)$/,''));await this.anchor(base);
      const target=path.join(root,version+'-'+this.platform+'-'+this.arch);let existing=false;try{await this.anchor(target);existing=true;}catch(e){if(e.code!=='ENOENT')throw e;}
      if(!existing){await this.directoryFor(['node']);await fs.rename(base,target);}
      const node=path.join(this.platform==='win32'?target:path.join(target,'bin'),this.platform==='win32'?'node.exe':'node');
      const checked=await this.run(node,['--version'],{timeout:10000,maxBuffer:4096,windowsHide:true,env:cleanEnvironment(this.env)});
      if(String(checked.stdout||'').trim()!=='v'+version)throw fail('TOOL_VERSION_MISMATCH');
      const state={version,platform:this.platform,arch:this.arch,sha256:sha256.toLowerCase(),binarySha256:digest(await readSafe(node,256*1024*1024))};
      const temp=path.join(root,'.current-'+randomUUID()+'.json');await fs.writeFile(temp,JSON.stringify(state)+'\n',{flag:'wx',mode:0o600});await this.directoryFor(['node']);await fs.rename(temp,path.join(root,'current.json'));
    }finally{try{await fs.rm(stage,{recursive:true,force:true});}catch{}}
    await this.applyEnvironment();return this.managedNode();
  }
  async installCodex(){
    const env=await this.environment();const runtime=await this.systemNode(env)||await this.managedNode()||await this.downloadNode();
    if(!runtime)throw fail('TOOL_INSTALL_UNVERIFIED');
    const prefix=await this.directoryFor(['npm'],true),delimiter=this.platform==='win32'?';':':';
    this.emit('codex','installing','正在安裝 Codex（官方 npm 套件），約需一兩分鐘。');
    await this.run(runtime.node,[runtime.npmCli,'install','--prefix',prefix,'--save-exact','--no-audit','--no-fund','--registry','https://registry.npmjs.org','@openai/codex'],{cwd:prefix,timeout:900000,maxBuffer:8*1024*1024,windowsHide:true,env:{...cleanEnvironment(env),PATH:runtime.bin+delimiter+env.PATH,npm_config_update_notifier:'false'}});
    await this.applyEnvironment();const toolStatus=(await this.inspect()).tools.find(t=>t.id==='codex');
    if(toolStatus.status!=='ready')throw fail('TOOL_INSTALL_UNVERIFIED');
    this.emit('codex','installed','Codex 已安裝並驗證，可以到 AI 設定連接 ChatGPT。');return {state:'installed',tool:'codex',installed:true,toolStatus};
  }
  async managedGH(){try{await this.directoryFor(['gh']);const state=JSON.parse(await readSafe(path.join(this.directory,'gh/current.json')));if(!/^\d+\.\d+\.\d+$/.test(state.version)||state.platform!==this.platform||state.arch!==this.arch||!/^\w{64}$/.test(state.binarySha256))throw fail('INVALID_TOOL_STATE');const dir=await this.directoryFor(['gh',state.version+'-'+this.platform+'-'+this.arch,'bin']);const binary=path.join(dir,this.platform==='win32'?'gh.exe':'gh');if(digest(await readSafe(binary,256*1024*1024))!==state.binarySha256)throw fail('TOOL_BINARY_CHANGED');return {command:binary,args:[],source:'managed'};}catch(e){if(e.code==='ENOENT')return null;throw e;}}
  async nativeCodexDirectories(){const platformName='codex-'+this.platform+'-'+this.arch;const triple=this.platform==='win32'?(this.arch==='arm64'?'aarch64':'x86_64')+'-pc-windows-msvc':(this.arch==='arm64'?'aarch64':'x86_64')+'-apple-darwin';const roots=[...(this.platform==='win32'&&this.env.APPDATA?[path.join(this.env.APPDATA,'npm/node_modules')]:[]),path.join(this.directory,'npm/node_modules')];const candidates=roots.flatMap(root=>[path.join(root,'@openai',platformName,'vendor',triple,'bin'),path.join(root,'@openai',platformName,'vendor',triple,'codex'),path.join(root,'@openai/codex/node_modules/@openai',platformName,'vendor',triple,'bin'),path.join(root,'@openai/codex/node_modules/@openai',platformName,'vendor',triple,'codex')]);return candidates.filter(Boolean);}
  async environment(){const env={...this.env};let managed;try{managed=await this.managedGH();}catch(e){if(e.code!=='ENOENT')throw e;}const dirs=await this.conventionalDirectories();for(const dir of await this.nativeCodexDirectories()){try{if((await fs.stat(dir)).isDirectory())dirs.unshift(dir);}catch{}}let node=null;try{node=await this.managedNode();}catch{}if(node)dirs.unshift(node.bin);if(managed)dirs.unshift(path.dirname(managed.command));const delimiter=this.platform==='win32'?';':':';env.PATH=[...new Set(dirs)].join(delimiter);if(this.platform==='win32')for(const key of Object.keys(env)){if(key!=='PATH'&&key.toLowerCase()==='path')delete env[key];}return env;}
  async applyEnvironment(){const env=await this.environment();this.env.PATH=env.PATH;if(this.platform==='win32')for(const key of Object.keys(this.env)){if(key!=='PATH'&&key.toLowerCase()==='path')delete this.env[key];}return env;}
  async locate(name,dirs){for(const dir of dirs){const file=path.join(dir,name);if(await exists(file))return file;}return null;}
  async resolveCommand(id,context={}){tool(id);const env=context.env||await this.environment();if(id==='wrangler')return {command:process.execPath,args:[path.resolve(__dirname,'../../../node_modules/wrangler/wrangler-dist/cli.js')],env:{...env,ELECTRON_RUN_AS_NODE:'1',WRANGLER_SEND_METRICS:'false'},source:'bundled'};if(id==='gh'){const managed=Object.hasOwn(context,'managedGH')?context.managedGH:await this.managedGH();if(managed)return {...managed,env};}
    const dirs=env.PATH.split(this.platform==='win32'?';':':');const extension=this.platform==='win32'?'.exe':'';let command=await this.locate(id+extension,dirs);
    if(command)return {command,args:[],env,source:command.startsWith(this.directory+path.sep)?'managed':'system'};
    if(['codex','gemini','claude'].includes(id)){const entry={codex:'@openai/codex/bin/codex.js',gemini:'@google/gemini-cli/dist/index.js',claude:'@anthropic-ai/claude-code/cli.js'}[id];const roots=[path.join(this.directory,'npm/node_modules'),...(this.platform==='win32'&&this.env.APPDATA?[path.join(this.env.APPDATA,'npm/node_modules')]:[])];const node=await this.locate('node'+extension,dirs);for(const root of roots){const script=path.join(root,entry);if(node&&await exists(script))return {command:node,args:[script],env,source:root.startsWith(this.directory+path.sep)?'managed':'system'};}}
    return null;
  }
  async inspect(){let context;try{context={env:await this.environment(),managedGH:await this.managedGH()};}catch{context=null;}const patterns={node:/^v(\d+\.\d+\.\d+)/,git:/^git version (\d+\.\d+\.\d+)/,gh:/^gh version (\d+\.\d+\.\d+)/,codex:/^codex-cli (\d+\.\d+\.\d+)/,claude:/(\d+\.\d+\.\d+)/,gemini:/(\d+\.\d+\.\d+)/,wrangler:/(?:^|\n)(\d+\.\d+\.\d+)(?:\s|$)/};const tools=await Promise.all(Object.keys(LABELS).map(async id=>{let resolved;try{resolved=await this.resolveCommand(id,context||{});if(!resolved)throw fail('MISSING_TOOL');if(id==='git'&&this.platform==='darwin'&&resolved.command==='/usr/bin/git')await this.run('/usr/bin/xcode-select',['-p'],{timeout:3000,maxBuffer:4096,env:resolved.env});let version=null;try{const output=await this.run(resolved.command,[...resolved.args,'--version'],{env:resolved.env,timeout:8000,maxBuffer:8192,windowsHide:true});version=patterns[id].exec(String(output.stdout||'').trim())?.[1]||null;}catch(error){if(!['codex','claude'].includes(id))throw error;}const supported=['codex','claude'].includes(id)||version&&(id!=='gemini'||version===GEMINI_VERSION)&&(id!=='wrangler'||version===WRANGLER_VERSION)&&(id!=='node'||Number(version.split('.')[0])>=20);return {id,label:LABELS[id],status:supported?'ready':'unsupported',version,source:resolved.source,requiredVersion:({gemini:GEMINI_VERSION,wrangler:WRANGLER_VERSION})[id]||null,setupUrl:SOURCES[id],action:supported?(id==='wrangler'?'connect-cloudflare':id==='gh'?'connect-github':['codex','claude','gemini'].includes(id)?'connect-ai':'ready'):id==='wrangler'?'repair-app':'install'};}catch{return {id,label:LABELS[id],status:'missing',version:null,source:resolved?.source||null,requiredVersion:({gemini:GEMINI_VERSION,wrangler:WRANGLER_VERSION})[id]||null,setupUrl:SOURCES[id],action:id==='wrangler'?'repair-app':'install'};}}));return {tools,platform:this.platform};}
  recipe(id){const prefix=path.join(this.directory,'npm');if(this.platform==='darwin'){
    const brew='if [ ! -x /opt/homebrew/bin/brew ] && [ ! -x /usr/local/bin/brew ]; then\n  /bin/bash -c "$(/usr/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"\nfi\nif [ -x /opt/homebrew/bin/brew ]; then TP_BREW=/opt/homebrew/bin/brew; else TP_BREW=/usr/local/bin/brew; fi\n';
    const node='if ! command -v node >/dev/null 2>&1 || [ "$(node -p "Number(process.versions.node.split(\'.\')[0]) >= 20")" != true ]; then\n'+brew+'  "$TP_BREW" install node@24\nfi\nexport PATH="/opt/homebrew/opt/node@24/bin:/usr/local/opt/node@24/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"\n';
    const commands={git:'/usr/bin/xcode-select --install\nprintf "\\n請完成 macOS 的工具安裝視窗，再回到 App 重新檢查。\\n"',node:node+'node --version',claude:'/usr/bin/curl -fsSL https://claude.ai/install.sh | /bin/bash',codex:node+'npm install --prefix '+sh(prefix)+' --save-exact --no-audit --no-fund --registry https://registry.npmjs.org @openai/codex',gemini:node+'npm install --prefix '+sh(prefix)+' --save-exact --no-audit --no-fund --registry https://registry.npmjs.org @google/gemini-cli@'+GEMINI_VERSION};return '#!/bin/bash\nset -euo pipefail\n'+commands[id]+'\nprintf "\\n完成後請回到 Travel Planner，按「重新檢查」。\\n"\n';
  }if(this.platform==='win32'){
    const winget="if (-not (Get-Command winget -ErrorAction SilentlyContinue)) { Start-Process 'https://aka.ms/getwinget'; throw '請先完成 Microsoft 應用程式安裝程式，再回到 App 重試。' }\n";
    const node=winget+"$TP_NodeReady=$false; if (Get-Command node -ErrorAction SilentlyContinue) { try { $TP_NodeReady=[int]((node --version).TrimStart('v').Split('.')[0]) -ge 20 } catch {} }; if (-not $TP_NodeReady) { winget install --id OpenJS.NodeJS.LTS --exact --source winget; if ($LASTEXITCODE -ne 0) { throw 'Node.js 安裝尚未完成' } }\n$env:Path = [Environment]::GetEnvironmentVariable('Path','Machine')+';'+[Environment]::GetEnvironmentVariable('Path','User')\nif (-not (Get-Command npm.cmd -ErrorAction SilentlyContinue)) { throw '請關閉此視窗，回到 App 重新檢查 Node.js 後再試。' }\n";
    const commands={git:winget+"winget install --id Git.Git --exact --source winget\nif ($LASTEXITCODE -ne 0) { throw 'Git 安裝尚未完成' }",node:node+'node --version',claude:"& ([scriptblock]::Create((Invoke-RestMethod 'https://claude.ai/install.ps1')))",codex:node+'npm.cmd install --prefix '+ps(prefix)+' --save-exact --no-audit --no-fund --registry https://registry.npmjs.org @openai/codex',gemini:node+'npm.cmd install --prefix '+ps(prefix)+' --save-exact --no-audit --no-fund --registry https://registry.npmjs.org @google/gemini-cli@'+GEMINI_VERSION};return "$ErrorActionPreference='Stop'\n"+commands[id]+"\nif ($LASTEXITCODE -and $LASTEXITCODE -ne 0) { throw '工具安裝尚未完成，請查看上方訊息。' }\nWrite-Host '完成後請回到 Travel Planner，按「重新檢查」。'\n";
  }throw fail('UNSUPPORTED_TOOL_PLATFORM');}
  async prepare(id){tool(id);if(!['darwin','win32'].includes(this.platform))throw fail('UNSUPPORTED_TOOL_PLATFORM');await this.directoryFor([],true);for(const [token,plan] of this.plans)if(plan.expiresAt<this.now())this.plans.delete(token);if(this.plans.size>=8)throw fail('INSTALL_PLAN_LIMIT');const token=randomUUID();let plan={token,tool:id,label:LABELS[id],expiresAt:this.now()+10*60*1000,sourceUrl:SOURCES[id]};
    if(id==='wrangler')plan={...plan,method:'bundled',commandPreview:'使用 Travel Planner 內建的 Wrangler 4.135.0',steps:['Wrangler 已隨 App 提供，不需要另外安裝。','到網站發布設定連接 Cloudflare，並親自完成官方授權。']};
    else if(id==='gh'){
      if(!['x64','arm64'].includes(this.arch))throw fail('UNSUPPORTED_TOOL_PLATFORM');const metadataBytes=await this.download('https://api.github.com/repos/cli/cli/releases/latest',{maxBytes:1024*1024,timeoutMs:15000});if(!Buffer.isBuffer(metadataBytes)||metadataBytes.length>1024*1024)throw fail('TOOL_DOWNLOAD_TOO_LARGE');const release=JSON.parse(metadataBytes.toString('utf8'));if(release.draft||release.prerelease||!/^v\d+\.\d+\.\d+$/.test(release.tag_name)||!Array.isArray(release.assets))throw fail('INVALID_TOOL_RELEASE');const version=release.tag_name.slice(1),name='gh_'+version+'_'+(this.platform==='darwin'?'macOS':'windows')+'_'+(this.arch==='x64'?'amd64':'arm64')+'.zip',checksumName='gh_'+version+'_checksums.txt',base='https://github.com/cli/cli/releases/download/'+release.tag_name+'/';const asset=release.assets.find(a=>a.name===name),checksums=release.assets.find(a=>a.name===checksumName);if(!asset||!checksums||asset.browser_download_url!==base+name||checksums.browser_download_url!==base+checksumName||!Number.isSafeInteger(asset.size)||asset.size<=0||asset.size>64*1024*1024)throw fail('INVALID_TOOL_RELEASE');const sums=await this.download(checksums.browser_download_url,{maxBytes:65536,timeoutMs:15000});if(!Buffer.isBuffer(sums)||sums.length>65536)throw fail('INVALID_TOOL_CHECKSUM');const line=sums.toString('utf8').split(/\r?\n/).find(l=>l.trim().split(/\s+/).at(-1)===name);const sha256=line?.trim().split(/\s+/)[0];if(!/^[0-9a-f]{64}$/i.test(sha256||''))throw fail('INVALID_TOOL_CHECKSUM');plan={...plan,method:'managed-download',version,assetURL:asset.browser_download_url,assetName:name,bytes:asset.size,sha256:sha256.toLowerCase(),commandPreview:`下載 GitHub 官方 ${name}\n核對 SHA-256：${sha256}\n只安裝到 App 管理的工具目錄，再執行 gh --version 驗證。`,steps:['從 GitHub 官方 release 下載並核對檔案。','工具只放在這台電腦的 App 資料目錄，不改動系統 GitHub CLI。','安裝後重新驗證，接著可連接 GitHub 帳號。']};
    }else if(id==='codex'){await this.directoryFor(['npm'],true);plan={...plan,method:'managed-npm',commandPreview:'npm install --prefix '+sh(path.join(this.directory,'npm'))+' --save-exact --no-audit --no-fund --registry https://registry.npmjs.org @openai/codex',steps:['這台電腦若沒有 Node.js 20 以上，App 會先從 nodejs.org 下載官方 Node.js，核對檢查碼後放在 App 自己的工具資料夾。不需要管理員密碼，也不會安裝其他軟體。','接著在背景安裝官方 Codex 套件，完成後自動檢查版本，約需一兩分鐘。','裝好後到「AI 助手」按「連接 ChatGPT」，在官方頁面登入即可。']};}
    else if(id==='node'){plan={...plan,method:'managed-node',commandPreview:'從 https://nodejs.org/dist/latest-v24.x/ 下載官方 Node.js 24，核對 SHA-256 後放到 Travel Planner 的工具資料夾',steps:['下載官方 Node.js 並核對檢查碼。','放在 App 自己的工具資料夾，不需要管理員密碼，不影響電腦上其他程式。']};}
    else{await this.directoryFor(['npm'],true);plan={...plan,method:'terminal',commandPreview:this.recipe(id),steps:['開啟系統終端機，執行下方固定的官方安裝流程。','如需管理員密碼、系統安裝視窗或授權，請親自完成。','回到 App 按「重新檢查」，工具驗證通過才會標示已安裝。']};}
    this.plans.set(token,plan);return structuredClone(plan);
  }
  async install(token,{confirmed=false}={}){if(confirmed!==true)throw fail('TOOL_CONFIRMATION_REQUIRED');const plan=this.plans.get(token);if(!plan||plan.expiresAt<this.now())throw fail('INSTALL_PLAN_EXPIRED');if(this.busy)throw fail('TOOL_INSTALL_BUSY');this.plans.delete(token);this.busy=true;
    try{await this.directoryFor();if(plan.method==='bundled'){const item=(await this.inspect()).tools.find(t=>t.id===plan.tool);return {state:item.status==='ready'?'ready':'repair-app',tool:plan.tool,installed:false,toolStatus:item};}
      if(plan.method==='managed-npm')return await this.installCodex();
      if(plan.method==='managed-node'){await(await this.managedNode()||this.downloadNode());const toolStatus=(await this.inspect()).tools.find(t=>t.id==='node');return {state:toolStatus.status==='ready'?'installed':'repair-app',tool:'node',installed:toolStatus.status==='ready',toolStatus};}
      if(plan.method==='terminal'){const dir=await this.directoryFor(['recipes'],true);const file=path.join(dir,token+(this.platform==='darwin'?'.command':'.ps1'));await fs.writeFile(file,plan.commandPreview,{flag:'wx',mode:0o700});await this.directoryFor(['recipes']);this.emit(plan.tool,'opening-terminal','正在開啟系統安裝視窗。');await this.openTerminal({platform:this.platform,scriptPath:file,script:plan.commandPreview,env:cleanEnvironment(await this.environment())});return {state:'terminal-opened',tool:plan.tool,installed:false,message:'安裝視窗已開啟；完成後請回到 App 重新檢查。'};}
      this.emit('gh','downloading','正在下載 GitHub 官方工具。');const bytes=await this.download(plan.assetURL,{maxBytes:64*1024*1024,timeoutMs:120000});if(!Buffer.isBuffer(bytes)||bytes.length!==plan.bytes||digest(bytes)!==plan.sha256)throw fail('TOOL_CHECKSUM_MISMATCH');const root=await this.directoryFor(['gh'],true);const stage=path.join(root,'.stage-'+randomUUID());await fs.mkdir(stage,{mode:0o700});let staging=true;
      try{const archive=path.join(stage,'gh.zip'),expanded=path.join(stage,'expanded');await fs.writeFile(archive,bytes,{flag:'wx',mode:0o600});await fs.mkdir(expanded,{mode:0o700});this.emit('gh','verifying','檔案核對通過，正在檢查工具版本。');await this.extract(archive,expanded,{platform:this.platform,run:this.run});const base=this.platform==='darwin'?path.join(expanded,plan.assetName.slice(0,-4)):expanded;for(const dir of [stage,expanded,base,path.join(base,'bin')])await this.anchor(dir);const source=path.join(base,'bin',this.platform==='win32'?'gh.exe':'gh');const binary=await readSafe(source,256*1024*1024);await fs.chmod(source,0o700);const checked=await this.run(source,['--version'],{timeout:10000,maxBuffer:8192,windowsHide:true,env:cleanEnvironment(await this.environment())});if(!String(checked.stdout||'').startsWith('gh version '+plan.version+' '))throw fail('TOOL_VERSION_MISMATCH');const name=plan.version+'-'+this.platform+'-'+this.arch;const target=path.join(root,name);let existing=false;try{await this.anchor(target);existing=true;}catch(e){if(e.code!=='ENOENT')throw e;}
        if(!existing){const bundle=path.join(stage,'bundle');await fs.mkdir(path.join(bundle,'bin'),{recursive:true,mode:0o700});await fs.writeFile(path.join(bundle,'bin',path.basename(source)),binary,{flag:'wx',mode:0o700});await this.directoryFor(['gh']);await fs.rename(bundle,target);}else{const current=await readSafe(path.join(target,'bin',path.basename(source)),256*1024*1024);if(digest(current)!==digest(binary))throw fail('TOOL_BINARY_CHANGED');}
        const state={version:plan.version,platform:this.platform,arch:this.arch,sha256:plan.sha256,binarySha256:digest(binary)};const temp=path.join(root,'.current-'+randomUUID()+'.json');await fs.writeFile(temp,JSON.stringify(state)+'\n',{flag:'wx',mode:0o600});await this.directoryFor(['gh']);try{const current=await fs.lstat(path.join(root,'current.json'));if(!current.isFile()||current.isSymbolicLink()||current.nlink!==1)throw fail('UNSAFE_TOOL_FILE');}catch(e){if(e.code!=='ENOENT')throw e;}await fs.rename(temp,path.join(root,'current.json'));await this.applyEnvironment();const toolStatus=(await this.inspect()).tools.find(t=>t.id==='gh');if(toolStatus.status!=='ready'||toolStatus.version!==plan.version)throw fail('TOOL_VERSION_MISMATCH');this.emit('gh','installed','GitHub CLI 已安裝並驗證，可以連接帳號。');return {state:'installed',tool:'gh',installed:true,toolStatus};
      }finally{if(staging){try{await this.directoryFor(['gh']);await this.anchor(stage);await fs.rm(stage,{recursive:true});}catch{}}}
    }catch(e){this.emit(plan.tool,'failed','工具安裝尚未完成，請重新檢查或重試。');throw e;}finally{this.busy=false;}}
}
async function prepareToolEnvironment(userData,options={}){const support=new ToolSupport(userData,options);return support.applyEnvironment();}
module.exports={ToolSupport,prepareToolEnvironment,SOURCES,GEMINI_VERSION};
