// Full desktop flows with fake model/remote services and an isolated sample repo.
const {app}=require('electron');const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');const {EventEmitter}=require('node:events');
const {createWindow,shutdown}=require('./main.cjs');const {createProjectStore}=require('./project-store.cjs');const {NewTripService}=require('./services/new-trip.cjs');const {LocalArchiveService}=require('./services/local-archive.cjs');const {ProposalStore}=require('./proposals.cjs');const {parseLiteralModule}=require('@travel-planner/engine');
app.on('window-all-closed',()=>{});let win,root,timer,status=0;const js=s=>win.webContents.executeJavaScript(s);
async function until(s){for(let i=0;i<400;i++){if(await js(s))return;await new Promise(r=>setTimeout(r,30));}throw Error('Batch condition: '+s);}
async function shot(name){await js("new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");await new Promise(r=>setTimeout(r,100));await fs.mkdir(path.resolve(__dirname,'../../.local/desktop-prototype'),{recursive:true});await fs.writeFile(path.resolve(__dirname,'../../.local/desktop-prototype',name),(await win.webContents.capturePage()).toPNG());}
app.whenReady().then(async()=>{
 timer=setTimeout(()=>app.exit(1),90000);root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'travel-batch-')));const project=path.join(root,'project'),state=path.join(root,'state');
 await fs.mkdir(path.join(project,'scripts'),{recursive:true});await fs.writeFile(path.join(project,'package.json'),'{"name":"sample","version":"1.1.0"}');for(const f of ['build.js','check.js'])await fs.writeFile(path.join(project,'scripts',f),'throw Error("never execute");');
 const example=path.resolve(__dirname,'../../trips/_example');await fs.cp(example,path.join(project,'trips/sample'),{recursive:true});
 const ws=createProjectStore(state);await ws.connect({id:'batch',root:project});await ws.select('batch','sample');
 const ref=path.join(root,'reference.md');await fs.writeFile(ref,'# 參考\n希望每天都有休息空檔。');const archiveFile=path.join(root,'private.travel-planner.json');
 const account=new EventEmitter();account.account={state:'connected',label:'測試帳號',version:'0.155.1'};account.connect=async()=>account.account;account.stop=async()=>{};account.models=async()=>[{id:'fake',name:'測試模型',isDefault:true,effort:[{reasoningEffort:'low'},{reasoningEffort:'high'}]}];
 let setupConfirmed=0,identityConfirmed=0;let backupConfirmed=0,publishConfirmed=0,adoptConfirmed=0,turn=0;const inputs=[];
 const fakeBackup={prepare:async()=>({token:'backup-token',repo:'sample/private',branch:'main',files:[{path:'trips/sample/data.js',status:'present',bytes:10}],unpublishedCommits:1,unrelatedCommittedFiles:['README.md'],warnings:['還有既有提交']}),confirm:async token=>{assert.equal(token,'backup-token');backupConfirmed++;return {backedUp:true,message:'私人備份已完成，遠端版本已核對。'};}};
 const fakePublisher={accounts:async()=>({connected:true,accounts:[{id:'a'.repeat(32),name:'測試 Cloudflare'}],selectedAccountId:null}),setAccount:id=>({selectedAccountId:id}),prepare:async input=>{assert.equal(input.previewSeen,true);assert.match(input.previewOutputDigest,/^[a-f0-9]{64}$/);return {token:'publish-token',name:'sample-site',accountName:'測試 Cloudflare',warning:'持有網址的人可開啟'};},confirm:async(token,input)=>{assert.equal(token,'publish-token');assert.equal(input.previewSeen,true);assert.match(input.previewOutputDigest,/^[a-f0-9]{64}$/);publishConfirmed++;return {published:true,url:'https://sample.test.workers.dev/',message:'網站已發布'};},prepareAdoption:async()=>({token:'adopt-token',name:'sample-site',accountName:'測試帳號',versionId:'fake-version',warning:'確認歸屬'}),confirmAdoption:async()=>{adoptConfirmed++;return {adopted:true,message:'已接管，未發布'};}};
 const options={pickProjectParent:async()=>({canceled:false,filePaths:[root]}),makeProjectSetup:()=>({prepareIdentity:async()=>({token:'identity-token',repo:'sample/private',author:{name:'sample',email:'1+sample@users.noreply.github.com'},warning:'只設定此專案'}),confirmIdentity:async token=>{assert.equal(token,'identity-token');identityConfirmed++;return {ready:true,message:'備份署名已設定'};},prepareClone:async input=>({token:'setup-token',repo:input.repo,visibility:'PRIVATE',destination:project}),confirmClone:async token=>{assert.equal(token,'setup-token');setupConfirmed++;return {ready:true,root:project,repo:'sample/private'};}}),makeAuth:()=>({status:async provider=>({provider,connected:true,accounts:[],sharedWithCLI:true}),start:async()=>({started:true}),cancel:async()=>({}),close:async()=>{}}),stateDirectory:state,codexAccount:account,makeNewTrips:()=>new NewTripService({checkPrivate:async()=>true}),makeArchive:()=>new LocalArchiveService({checkPrivate:async()=>true}),makeBackup:()=>fakeBackup,makePublisher:()=>fakePublisher,makeProposals:d=>new ProposalStore(d,{checkPrivate:async()=>{}}),pickReferences:async()=>({canceled:false,filePaths:[ref]}),saveArchivePath:async()=>({canceled:false,filePath:archiveFile}),pickArchivePath:async()=>({canceled:false,filePaths:[archiveFile]}),fetchReference:async url=>({url,checkedAt:new Date().toISOString(),text:'This official source confirms the sample information for testing.'}),environmentService:{inspectEnvironment:async()=>({tools:[{id:'Codex',status:'ready',version:'0.155.1',setupUrl:'https://developers.openai.com/codex/cli/'}]}),checkForUpdates:async()=>({state:'unpublished'})},makeEditor:()=>({active:null,stop:async()=>({}),generate:async input=>{
   inputs.push(input);turn++;await input.onThread('fake-thread');await input.onTurn('fake-thread','turn-'+turn);const common={threadId:'fake-thread',turnId:'turn-'+turn,model:'fake'};
   if(input.mode==='research')return {...common,summary:'官方來源已列出。',research:true,sources:[{url:'https://example.com/source',title:'範例官方來源',evidence:'This official source confirms the sample information for testing.'}],unresolved:[],feasibility:'已檢查本測試行程的順序、停留時間及交通緩衝。'};
   if(input.mode==='planning')return {...common,summary:'以下是待你確認的草案。',planning:true,planMarkdown:'## 第一天\n- 保留午後休息\n\n## 第二天\n- 慢慢散步'};
   if(input.mode==='materialize'){const files={};for(const name of ['trip.config.json','data.js','details.js','dining.js','map-lists.js','photos.json','theme.css','extra.js']){try{files[name]=await fs.readFile(path.join(example,name),'utf8');}catch{if(['theme.css','extra.js'].includes(name))continue;throw Error('missing fixture');}}const config=JSON.parse(files['trip.config.json']);config.title=input.planningDraft.title;config.deploy.name=input.planningDraft.slug;files['trip.config.json']=JSON.stringify(config);return {...common,summary:'已建立可供確認的完整候選。',materialize:true,files};}
   const days=parseLiteralModule(input.snapshot.dataSource).DAYS;
   if(input.dayId===-1)return {...common,summary:'## 跨日調整\n\n| 日期 | 調整 |\n| --- | --- |\n| 每天 | 標題 |',replacementDays:days.map(d=>({...d,title:d.title+'・慢遊'}))};
   return {...common,summary:'已閱讀參考資料。',discussion:true};
 }})};
 win=await createWindow(options);win.webContents.setBackgroundThrottling(false);await until('realPreview?.status === "ready"');await js('codexAction("connectCodex")');await until('!document.getElementById("message").disabled');
 await js('document.getElementById("open-references").click()');await until('document.getElementById("references-dialog").open');await js('document.getElementById("add-reference-file").click()');await until('document.querySelectorAll("#references-list .reference-row").length===1');await js('document.getElementById("close-references").click();document.getElementById("chat-effort").value="high";document.getElementById("chat-effort").dispatchEvent(new Event("change"));document.getElementById("edit-day").value="-1";document.getElementById("edit-day").dispatchEvent(new Event("change"));document.getElementById("message").value="把每天標題調整得輕鬆一些";document.getElementById("chat-form").requestSubmit()');
 await until('pendingProposal && !aiBusy');assert.equal(inputs[0].mode,'edit-all');assert.equal(inputs[0].effort,'high');assert.equal(inputs[0].attachments.length,1);assert.equal(inputs[0].attachments[0].text.includes('休息'),true);assert.ok(await js('document.querySelector(".message-table table")!==null'));
 await js('document.getElementById("discard-proposal").click()');await until('!pendingProposal && realPreview?.status==="ready" && !aiBusy');
 await js('document.getElementById("open-settings").click();document.querySelector("[data-setting=sync]").click();document.querySelector("[data-sync-tab=backup]").click();document.getElementById("backup-prepare").click()');await until('!document.getElementById("backup-confirm").hidden');assert.equal(backupConfirmed,0);assert.ok(await js('document.getElementById("backup-review").textContent.includes("README.md")'));await js('document.getElementById("backup-confirm").click()');await until('document.getElementById("backup-result").textContent.includes("已完成")');assert.equal(backupConfirmed,1);await js('document.getElementById("identity-prepare").click()');await until('!document.getElementById("identity-confirm").hidden');assert.equal(identityConfirmed,0);await js('document.getElementById("identity-confirm").click()');await until('document.getElementById("identity-result").textContent.includes("已設定")');assert.equal(identityConfirmed,1);await new Promise(r=>setTimeout(r,200));
 await js('document.getElementById("archive-export").click()');await until('document.getElementById("backup-result").textContent.includes("已匯出")');assert.ok((await fs.stat(archiveFile)).size>0);
 await js('document.querySelector("[data-setting=sync]").click();document.querySelector("[data-sync-tab=publish]").click();document.getElementById("publish-prepare").click()');await until('!document.getElementById("publish-confirm").hidden');assert.equal(publishConfirmed,0);await js('document.getElementById("publish-ack").checked=true;document.getElementById("publish-confirm").click()');await until('document.getElementById("publish-result").textContent.includes("已發布")');assert.equal(publishConfirmed,1);
 await js('document.getElementById("adoption-prepare").click()');await until('!document.getElementById("adoption-confirm").hidden');await js('document.getElementById("adoption-confirm").click()');await until('document.getElementById("publish-result").textContent.includes("已接管")');assert.equal(adoptConfirmed,1);
 await js('document.querySelector("[data-setting=tools]").click()');await until('document.getElementById("environment-list").textContent.includes("0.155.1")');await js('document.getElementById("check-updates").click()');await until('document.getElementById("update-result").textContent.includes("尚未發布")');await shot('batch-tools.png');
 await js('document.getElementById("back-to-trip").click();document.getElementById("new-demo").click();document.getElementById("new-kind").value="real";document.getElementById("new-title").value="正式規劃測試";document.getElementById("new-destination").value="尚待討論的目的地";document.getElementById("new-form").requestSubmit()');await until('selected?.trip.title === "正式規劃測試" && realPreview?.planning');const newSlug=await js('selected.trip.slug');assert.ok(await fs.stat(path.join(project,'trips',newSlug,'docs/planning-draft.json')));
 await until('!document.getElementById("message").disabled');await js('document.getElementById("message").value="請整理成兩天的逐日草案";document.getElementById("chat-form").requestSubmit()');await until('selected.trip.featureState?.plan?.markdown && !aiBusy');assert.equal(await js('document.getElementById("materialize-plan").disabled'),true);await js('document.getElementById("confirm-plan").click()');await until('selected.trip.featureState.plan.approvedDigest');
 await js('document.getElementById("research-trip").click()');await until('selected.trip.featureState?.research && !aiBusy');await js('document.getElementById("show-research").click()');await until('!document.getElementById("confirm-research").disabled');await shot('batch-research.png');await js('document.getElementById("confirm-research").click()');await until('selected.trip.featureState.research.confirmed');
 await js('document.getElementById("materialize-plan").click()');await until('window.hasMaterialization() && !aiBusy');await until('!document.getElementById("confirm-materialization").disabled');assert.equal(JSON.parse(await fs.readFile(path.join(project,'trips',newSlug,'docs/planning-draft.json'),'utf8')).status,'planning');await js('document.getElementById("confirm-materialization").click()');await until('realPreview?.status==="ready" && !realPreview.planning && !window.hasMaterialization()');assert.equal(JSON.parse(await fs.readFile(path.join(project,'trips',newSlug,'docs/planning-draft.json'),'utf8')).status,'ready');
 await js('document.getElementById("handoff-open").click()');await until('document.getElementById("handoff-dialog").open');await js('document.getElementById("confirm-handoff").click()');await until('!document.getElementById("handoff-dialog").open && selected.trip.featureState.handoff');
 await until('document.querySelectorAll("#conversation-list .conversation-button").length>=1');const oldConversation=await js('selected.trip.featureState.conversationId');
 await js('document.getElementById("conversation-new").click()');await until('selected.trip.featureState.conversationId && selected.trip.featureState.conversationId !== '+JSON.stringify(oldConversation));assert.equal(await js('selected.trip.conversation.length'),0);const staleDraft=await js(`travelDesktop.saveConversationPreferences({...conversationTarget(),conversationId:${JSON.stringify(oldConversation)},draft:'不得覆蓋的新草稿'})`);assert.equal(staleDraft.code,'STALE_CONVERSATION');assert.equal((await js('travelDesktop.readConversation(conversationTarget())')).conversation.draft,'');
 await js('document.getElementById("conversation-rename").click();document.getElementById("conversation-name").value="另一種旅行節奏";document.getElementById("conversation-name-form").requestSubmit()');await until('selected.trip.featureState.conversationTitle === "另一種旅行節奏"');
 await js('document.getElementById("conversation-archive").click()');await until('selected.trip.featureState.conversationTitle === "新的討論"');await js('document.getElementById("conversation-show-archived").click()');await until('document.getElementById("conversation-list").textContent.includes("已封存")');
 await js('document.getElementById("open-settings").click();document.querySelector("[data-setting=sync]").click();document.querySelector("[data-sync-tab=backup]").click();document.getElementById("archive-import").click()');await until('project.trips.length===3 && document.getElementById("settings").hidden && realPreview?.status==="ready"');
 await js('document.getElementById("open-settings").click();document.querySelector("[data-setting=projects]").click();document.getElementById("setup-repository").value="sample/private";document.getElementById("setup-clone").click()');await until('!document.getElementById("setup-confirm").hidden');assert.equal(setupConfirmed,0);await js('document.getElementById("setup-confirm").click()');await until('selected===null && !document.getElementById("welcome").hidden');assert.equal(setupConfirmed,1);assert.equal(await js('document.getElementById("message").value'),'');assert.equal(await js('document.getElementById("send-message").disabled'),true);
 console.log(JSON.stringify({passed:true,fakeExternalOnly:true,multiDay:true,markdown:true,effort:true,attachments:true,privateBackupConfirmation:true,publicPublishConfirmation:true,adoptionConfirmation:true,archiveExport:true,archiveImportNewTrip:true,environment:true,updates:true,realNewDraft:true,planGate:true,researchGate:true,materializePreviewGate:true,handoff:true,multipleConversations:true,renameArchive:true,projectDownloadConfirmation:true,newProjectClearsOldConversation:true}));
}).catch(async e=>{console.error(e);if(win&&!win.isDestroyed()){console.error(await js('JSON.stringify({aiBusy,realPreview,toast:document.getElementById("toast")?.textContent,publish:document.getElementById("publish-result").textContent})'));await shot('batch-failure.png');}status=1;}).finally(async()=>{clearTimeout(timer);if(win&&!win.isDestroyed())win.destroy();await shutdown();if(root)await fs.rm(root,{recursive:true,force:true});app.exit(status);});
