// Real pointer/keyboard events against the shared component, with no project/account.
const {app,BrowserWindow}=require('electron');const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');let win,status=0;
const state=require('node:fs').mkdtempSync(path.join(require('node:os').tmpdir(),'travel-menu-'));app.setPath('userData',state);app.on('window-all-closed',()=>{});
const js=s=>win.webContents.executeJavaScript(s);const settle=()=>new Promise(r=>setTimeout(r,70));
async function click(id){const p=await js(`(()=>{const r=document.getElementById(${JSON.stringify(id)}).getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...p});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...p});await settle();}
app.whenReady().then(async()=>{win=new BrowserWindow({show:true,width:640,height:400,webPreferences:{nodeIntegration:false,contextIsolation:true}});await win.loadURL('data:text/html,'+encodeURIComponent('<style>button{margin:20px;padding:12px}.action-menu{position:fixed;inset:auto;margin:0;padding:10px}.action-menu button{display:block;margin:0}</style><button id="a">A</button><button id="b">B</button><button id="outside">Outside</button>'));await js(await fs.readFile(path.join(__dirname,'menus.js'),'utf8'));await js('for(const id of ["a","b"]){const b=document.getElementById(id);b.onclick=()=>openActionMenu(b,[{label:id+" action",action:()=>{}}]);b.oncontextmenu=e=>openActionMenu(b,[{label:id+" context",action:()=>{}}],e);}void 0;');
await click('a');assert.equal(await js('!!document.querySelector(".action-menu:popover-open")'),true);
await click('a');assert.equal(await js('!!document.querySelector(".action-menu:popover-open")'),false,'clicking the same trigger must close the menu');assert.equal(await js('document.getElementById("a").getAttribute("aria-expanded")'),'false');
await click('a');await click('b');assert.equal(await js('document.querySelector(".action-menu").textContent'),'b action');assert.equal(await js('document.querySelectorAll(".action-menu").length'),1);
await click('outside');assert.equal(await js('!!document.querySelector(".action-menu")'),false);
await js('document.getElementById("a").click()');await js('document.getElementById("a").click()');assert.equal(await js('!!document.querySelector(".action-menu")'),false,'programmatic/keyboard activation toggles too');
await click('a');win.webContents.sendInputEvent({type:'keyDown',keyCode:'Escape'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Escape'});await settle();assert.equal(await js('!!document.querySelector(".action-menu")'),false);assert.equal(await js('document.activeElement.id'),'a');
await js('document.getElementById("a").dispatchEvent(new MouseEvent("contextmenu",{clientX:60,clientY:90,bubbles:true}))');await settle();assert.equal(await js('document.querySelector(".action-menu").textContent'),'a context');await click('a');assert.equal(await js('!!document.querySelector(".action-menu")'),false);
console.log(JSON.stringify({passed:true,sameTriggerToggles:true,otherTriggerSwitches:true,outsideDismiss:true,keyboardToggle:true,escapeFocus:true,contextMenu:true}));}).catch(e=>{console.error(e);status=1;}).finally(async()=>{win?.destroy();await fs.rm(state,{recursive:true,force:true,maxRetries:3,retryDelay:100}).catch(()=>{});app.exit(status);});
