// Native UI and persistence regression using only temporary sample data.
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');const {app}=require('electron');
const root=require('node:fs').realpathSync(require('node:fs').mkdtempSync(path.join(os.tmpdir(),'travel-navigation-')));process.env.TRAVEL_PLANNER_STATE_DIR=path.join(root,'app');
const {createWindow,shutdown}=require('./main.cjs');const {createProjectStore}=require('./project-store.cjs');const {TripTrashService}=require('./services/trip-trash.cjs');
let win,status=0,connections=0,installs=0,releaseOld;const providerAccounts={};app.on('window-all-closed',()=>{});
const js=async s=>{try{return await win.webContents.executeJavaScript(s);}catch(e){throw Error(s+" :: "+e.message);}};
async function until(s){for(let i=0;i<300;i++){if(await js(s))return;await new Promise(r=>setTimeout(r,30));}throw Error(s);}
async function shot(name){await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');await new Promise(r=>setTimeout(r,100));const folder=path.resolve(__dirname,'../../.local/desktop-navigation');await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,name),(await win.webContents.capturePage()).toPNG());}
async function resizeAndSettle(width,height){
 if(win.getSize()[0]!==width||win.getSize()[1]!==height)await new Promise((resolve,reject)=>{
   const onResize=()=>{clearTimeout(timer);resolve();};
   const timer=setTimeout(()=>{win.removeListener('resize',onResize);reject(Error('Window resize timed out'));},5000);
   win.once('resize',onResize);win.setSize(width,height);
 });
 await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
}
function account(provider='codex'){const a=new EventEmitter();a.account={state:'disconnected'};a.connect=async()=>{connections++;a.account={state:'connected',label:provider+'@example.invalid',version:'0.155.1'};a.emit('changed',a.account);return a.account;};a.stop=async()=>{};a.models=async()=>[{id:'fake',name:'測試模型',isDefault:true,effort:[]}];return a;}
app.whenReady().then(async()=>{
 const project=path.join(root,'project'),state=path.join(root,'state');await fs.mkdir(path.join(project,'scripts'),{recursive:true});await fs.writeFile(path.join(project,'package.json'),'{"name":"sample","version":"1.1.0"}');for(const f of ['check.js','build.js'])await fs.writeFile(path.join(project,'scripts',f),'throw Error("not executed");');await fs.cp(path.resolve(__dirname,'../../trips/_example'),path.join(project,'trips/sample'),{recursive:true});
 const store=createProjectStore(state);await store.connect({id:'nav',root:project});await store.select('nav','sample');
 const opts={makeToolSupport:()=>({applyEnvironment:async()=>process.env,resolveCommand:async()=>null,inspect:async()=>({tools:[{id:'gh',status:'missing',source:'system'},{id:'wrangler',version:'4.135.0',status:'ready',source:'bundled'}]}),prepare:async()=>({token:'tool-token',label:'GitHub',method:'terminal',commandPreview:'fixed-test-command',steps:['開啟安裝視窗','回來重新檢查']}),install:async(token,input)=>{assert.equal(token,'tool-token');assert.equal(input.confirmed,true);installs++;return {state:'terminal-opened',installed:false,message:'安裝視窗已開啟，請重新檢查。'};}}),stateDirectory:state,codexAccount:account(),makeProvider:id=>({account:providerAccounts[id]=account(id),editor:{active:null,stop:async()=>{}},capabilities:{images:false,switchAccount:false}}),makeTrash:()=>new TripTrashService({checkPrivate:async()=>true,checkIgnored:async()=>true})};
 win=await createWindow(opts);win.webContents.on("console-message",(_event,details)=>{if(details?.level==="error")console.error(details.message);});win.webContents.setBackgroundThrottling(false);await until('accountState.state==="connected" && realPreview?.status==="ready" && document.querySelector(".conversation-row")');assert.ok(connections>=1);
 assert.equal(await js('demos.length'),1);assert.equal(await js('document.getElementById("open-demo").offsetParent===null'),true);
 assert.equal(await js('document.getElementById("sidebar-toggle").previousElementSibling.classList.contains("brand")'),true);
 assert.equal(await js('document.querySelector("[data-trip=sample] #conversation-sidebar")!==null'),true);
 await js('document.getElementById("chat-more").click()');await until('document.querySelector(".action-menu")');assert.ok(await js('document.querySelector(".action-menu").textContent.includes("交接到新對話")'));
 await js('document.querySelector(".action-menu").dispatchEvent(new KeyboardEvent("keydown",{key:"End",bubbles:true}))');assert.equal(await js('document.activeElement.textContent'),'封存對話');await js('document.querySelector(".action-menu").dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');assert.equal(await js('document.activeElement.id'),'chat-more');
 await js('document.querySelector(".conversation-row").dispatchEvent(new MouseEvent("contextmenu",{bubbles:true,clientX:200,clientY:250}))');await until('document.querySelector(".action-menu")');await js('[...document.querySelectorAll(".action-menu button")].find(b=>b.textContent==="命名對話").click()');await until('document.getElementById("conversation-name-dialog").open');await js('document.getElementById("conversation-name").value="慢慢旅行";document.getElementById("conversation-name-form").requestSubmit()');await until('document.getElementById("conversation-list").textContent.includes("慢慢旅行")');
 assert.equal(await js('document.getElementById("conversation-title").textContent'),'慢慢旅行');assert.equal(await js('document.getElementById("conversation-header").contains(document.getElementById("chat-more"))'),true);assert.equal(await js('document.querySelectorAll(".message-label").length'),0);
 await js('addMessage({role:"user",text:"希望下午多留一點休息時間。"});addMessage({role:"assistant",text:"可以將午後安排放慢，保留自由活動的空檔。"});window.renderFeatureState({...selected.trip.featureState,job:{status:"paused"}})');assert.equal(await js('document.getElementById("chat-scroll").contains(document.getElementById("job-card"))'),true);assert.equal(await js('document.querySelector(".composer-region #job-card")'),null);assert.equal(await js('document.getElementById("job-card").hidden'),false);
 const sameRow=()=>js('(()=>{const a=document.getElementById("edit-day").getBoundingClientRect(),b=document.getElementById("research-trip").getBoundingClientRect();return b.left>=a.right && Math.abs((a.top+a.height/2)-(b.top+b.height/2))<2;})()');assert.equal(await sameRow(),true);
 await js('setTheme("dark")');await shot('chat-paused-dark.png');await js('setTheme("light")');await shot('chat-paused-light.png');win.setSize(860,700);await new Promise(r=>setTimeout(r,100));await js('document.getElementById("chat-scroll").scrollTop=document.getElementById("chat-scroll").scrollHeight');await shot('chat-paused-narrow.png');assert.equal(await sameRow(),true);assert.equal(await js('document.querySelector(".chat-column").scrollWidth<=document.querySelector(".chat-column").clientWidth'),true);await resizeAndSettle(1380,900);await js('window.renderFeatureState(selected.trip.featureState)');

 await js('setSidebar(false)');assert.equal(await js('document.getElementById("rail-settings").offsetParent!==null'),true);await js('setSidebar(true)');
 await js('document.querySelector("[data-trip=welcome-demo] .row-more").click()');await until('[...document.querySelectorAll(".action-menu button")].some(b=>b.textContent==="刪除示範旅程")');await js('[...document.querySelectorAll(".action-menu button")].find(b=>b.textContent==="刪除示範旅程").click()');await until('document.getElementById("trip-delete-dialog").open');await js('document.getElementById("confirm-trip-delete").click()');await until('demos.length===0 && !document.getElementById("trip-delete-dialog").open');assert.equal((await store.read()).state.demoHidden,true);
 await js('document.querySelector("[data-trip=sample] .journey-row > [aria-haspopup=menu]").click()');await js('[...document.querySelectorAll(".action-menu button")].find(b=>b.textContent==="移除旅程…").click()');await until('document.getElementById("trip-delete-dialog").open');await js('document.getElementById("confirm-trip-delete").click()');await until('project.trips.length===0 && selected===null');await assert.rejects(fs.stat(path.join(project,'trips/sample')));
 await js('document.getElementById("journeys-more").click()');await js('[...document.querySelectorAll(".action-menu button")].find(b=>b.textContent==="已移除的旅程…").click()');await until('document.getElementById("trip-trash-dialog").open');await js('document.querySelector("#trip-trash-list button").click()');await until('project.trips.length===1');assert.ok(await fs.stat(path.join(project,'trips/sample/data.js')));await js('document.getElementById("close-trip-trash").click()');
 await js('selectTrip(project.trips[0])');await until('realPreview?.status==="ready"');await js('document.getElementById("chat-more").click();[...document.querySelectorAll(".action-menu button")].find(b=>b.textContent==="使用其他 AI 開新對話…").click()');await until('document.getElementById("provider-switch-dialog").open');await js('document.getElementById("confirm-provider-switch").click()');await until('activeProvider==="claude" && accountState.state==="connected" && !aiBusy');assert.equal((await store.read()).state.aiProvider,'claude');await js('setTheme("dark")');await shot('chat-dark.png');await js('openSettings("tools")');await until('document.getElementById("environment-list").textContent.includes("GitHub")');await js('[...document.querySelectorAll("#environment-list button")].find(b=>b.textContent==="設定引導").click()');await until('document.getElementById("tool-setup-dialog").open');assert.equal(installs,0);await js('document.getElementById("tool-setup-confirm").click()');await until('document.getElementById("tool-setup-status").textContent.includes("重新檢查")');assert.equal(installs,1);await js('document.getElementById("close-tool-setup").click()');await shot('tools-dark.png');await js('openSettings("ai")');await shot('ai-dark.png');await js('openSettings("projects")');await shot('settings-dark.png');await js('setTheme("light")');await shot('settings-light.png');win.setSize(860,700);await shot('settings-narrow.png');
 win.destroy();await new Promise(r=>setTimeout(r,150));opts.codexAccount=undefined;win=await createWindow(opts);await until('document.documentElement.dataset.ready==="true" && accountState.state==="connected" && realPreview?.status==="ready"');assert.equal(await js('demos.length'),0);assert.equal(await js('activeProvider'),'claude');providerAccounts.claude.connect=()=>new Promise(resolve=>{releaseOld=resolve;});await js('void restoreAIConnection()');await until('accountState.state==="checking"');await js('document.getElementById("chat-provider").value="gemini";document.getElementById("chat-provider").dispatchEvent(new Event("change"))');await until('activeProvider==="gemini" && accountState.state==="connected" && !aiBusy');releaseOld({state:'connected',label:'stale@example.invalid'});await new Promise(r=>setTimeout(r,100));assert.equal(await js('accountState.label'),'gemini@example.invalid');
 console.log(JSON.stringify({passed:true,startupRestoresLogin:true,tripConversationTree:true,menusKeyboardAndContext:true,demoDeletionPersists:true,tripTrashRestore:true,collapsedSettings:true,providerSwitchAndRestore:true,toolSetupConfirmation:true,staleProviderReplyIgnored:true,conversationHeader:true,noAssistantName:true,inlineWorkStatus:true,researchSameRow:true,visuals:['dark','light','narrow']}));
}).catch(async e=>{console.error(e);if(win&&!win.isDestroyed()){console.error(await js('JSON.stringify({notice:document.getElementById("notification").textContent,accountState,ready:document.documentElement.dataset.ready})'));await shot('failure.png');}status=1;}).finally(async()=>{releaseOld?.({state:'disconnected'});if(win&&!win.isDestroyed())win.destroy();await shutdown();await fs.rm(root,{recursive:true,force:true});app.exit(status);});
