const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{app}=require('electron');
if(!process.env.TRAVEL_PLANNER_TEST_ROOT)throw Error('Run settings smoke through the native smoke runner');
const root=require('node:fs').realpathSync(process.env.TRAVEL_PLANNER_TEST_ROOT);process.env.TRAVEL_PLANNER_STATE_DIR=path.join(root,'app');
const {createWindow,shutdown}=require('./main.cjs'),{createProjectStore}=require('./project-store.cjs'),{ConversationStore}=require('./conversation-store.cjs');let win,status=0;app.on('window-all-closed',()=>{});
const js=async s=>{try{return await win.webContents.executeJavaScript(s);}catch(e){throw Error(s+' :: '+e.message);}};
async function until(s){for(let i=0;i<300;i++){if(await js(s))return;await new Promise(r=>setTimeout(r,30));}throw Error('Condition: '+s);}
async function shot(name){await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');await new Promise(r=>setTimeout(r,100));const dir=path.resolve(__dirname,'../../.local/desktop-settings');await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,name),(await win.webContents.capturePage()).toPNG());}
let logins=[],geminiConnections=0;const instances={};
function makeAccount(id){const a=new EventEmitter();a.account={provider:id,state:id==='codex'?'connected':'needs-login',label:id==='codex'?'sample@example.invalid':null};a.connect=async()=>{if(id==='gemini')geminiConnections++;return a.account;};a.refresh=a.connect;a.stop=async()=>{};a.models=async()=>a.account.state==='connected'?[{id:'default-'+id,name:'預設模型',isDefault:true,...(id==='codex'?{effort:['low','medium','high'],defaultEffort:'low'}:{effort:[]})},{id:'other-'+id,name:'另一個模型',effort:id==='codex'?['low','high']:[]}]:[];a.login=async()=>{logins.push(id);a.account={...a.account,state:'connected',label:id+'@example.invalid'};a.emit('changed',a.account);return {account:a.account};};a.cancelLogin=async()=>a.account;instances[id]=a;return a;}
app.whenReady().then(async()=>{
 const project=path.join(root,'project'),state=path.join(root,'state');await fs.mkdir(path.join(project,'scripts'),{recursive:true});await fs.writeFile(path.join(project,'package.json'),'{"name":"My journeys","version":"1.1.0"}');for(const f of ['build.js','check.js'])await fs.writeFile(path.join(project,'scripts',f),'throw Error("not executed");');await fs.cp(path.resolve(__dirname,'../../trips/_example'),path.join(project,'trips/sample'),{recursive:true});
 const store=createProjectStore(state);await store.connect({id:'settings',root:project});await store.select('settings','sample');await store.setAIDefaults({provider:'gemini',models:{},effort:'medium'});
 const options={stateDirectory:state,codexAccount:makeAccount('codex'),makeProvider:id=>({account:makeAccount(id),editor:{active:null,stop:async()=>{}},capabilities:{switchAccount:false}}),makeToolSupport:()=>({applyEnvironment:async()=>process.env,resolveCommand:async()=>null,inspect:async()=>({tools:[{id:'gh',version:'2.87.0',status:'ready'},{id:'wrangler',version:'4.135.0',status:'ready',source:'bundled'},{id:'claude',version:'2.1.278',status:'ready'},{id:'gemini',version:'0.46.0',status:'ready'}]})}),makeAuth:()=>({status:async()=>({connected:true}),close:async()=>{}}),makePublisher:()=>({accounts:async()=>({accounts:[],selectedAccountId:null})})};
 win=await createWindow(options);win.webContents.setBackgroundThrottling(false);await until('realPreview?.status==="ready" && accountState.state==="connected" && !conversationLoading');
 await until('document.querySelector("#settings-provider option[value=claude]").hidden && document.querySelector("#provider-switch-choice option[value=gemini]").hidden');await js('document.getElementById("chat-more").click();[...document.querySelectorAll(".action-menu button")].find(b=>b.textContent==="使用其他 AI 開新對話…").click()');await until('document.getElementById("notification").textContent.includes("沒有其他已連接")');assert.equal(await js('document.getElementById("provider-switch-dialog").open'),false);
 const original=await js('selected.trip.conversationId');await js('document.getElementById("message").value="目前對話的草稿";document.getElementById("message").dispatchEvent(new Event("input"));openSettings("ai")');await until('document.querySelectorAll("#provider-accounts .provider-row").length===2 && document.getElementById("provider-row-claude").textContent.includes("未連接") && !document.querySelector("#provider-row-claude [data-provider-action=connect]").disabled');assert.equal(await js('document.getElementById("provider-row-gemini")'),null);assert.deepEqual(await js('[...document.querySelectorAll("#settings-provider,#chat-provider,#provider-switch-choice")].map(s=>s.querySelector("option[value=gemini]").hidden)'),[true,true,true]);
 assert.deepEqual(await js('[...document.getElementById("settings-provider").options].filter(o=>!o.hidden).map(o=>o.value)'),['codex']);assert.equal(await js('document.getElementById("settings-provider").value'),'codex');assert.equal((await store.read()).state.aiDefaults.provider,'gemini');assert.equal(await js('document.getElementById("defaults-effort").value'),'medium');await js('document.getElementById("defaults-effort").value="high";document.getElementById("defaults-effort").dispatchEvent(new Event("change"))');await until('document.getElementById("defaults-status").textContent==="已保存"');assert.equal((await store.read()).state.aiDefaults.effort,'high');
 await js('document.querySelector("#provider-row-claude [data-provider-action=connect]").click()');await until('document.getElementById("provider-row-claude").textContent.includes("已連接")');assert.deepEqual(logins,['claude']);assert.deepEqual(await js('[...document.getElementById("settings-provider").options].filter(o=>!o.hidden).map(o=>o.value)'),['codex','claude']);assert.equal(await js('activeProvider'),'codex');assert.equal(await js('selected.trip.conversationId'),original);assert.equal(await js('document.getElementById("message").value'),'目前對話的草稿');
 const hiddenLogin=await js('window.travelDesktop.feature("provider-account-action",{id:"gemini",action:"login"})');assert.equal(hiddenLogin.ok,false);assert.equal((await js('window.travelDesktop.feature("provider-select",{id:"gemini",newConversation:true})')).ok,false);assert.equal((await js('window.travelDesktop.feature("ai-defaults-set",{provider:"gemini"})')).ok,false);assert.deepEqual(logins,['claude']);
 await js('document.getElementById("settings-provider").value="claude";document.getElementById("settings-provider").dispatchEvent(new Event("change"))');await until('document.getElementById("defaults-status").textContent==="已保存" && document.getElementById("defaults-model").options.length===3');await js('document.getElementById("defaults-model").value="other-claude";document.getElementById("defaults-model").dispatchEvent(new Event("change"))');await until('document.getElementById("defaults-status").textContent==="已保存"');assert.deepEqual((await store.read()).state.aiDefaults,{provider:'claude',models:{claude:'other-claude'},effort:'high'});assert.equal(await js('activeProvider'),'codex');
 assert.equal(await js('document.querySelector("#provider-row-codex .inline-heading").contains(document.querySelector("#provider-row-codex .status-pill"))'),true);await js('setTheme("dark")');await shot('ai-dark.png');await js('setTheme("light")');await shot('ai-light.png');
 await js('closeSettings()');await until('!document.getElementById("conversation-new").disabled && !aiBusy');await js('document.getElementById("conversation-new").click()');await until('activeProvider==="claude" && selected.trip.conversationId!=='+JSON.stringify(original)+' && document.getElementById("chat-model").value==="other-claude" && !aiBusy');assert.deepEqual(await js('[...document.getElementById("chat-provider").options].filter(o=>!o.hidden).map(o=>o.value)'),['codex','claude']);await js('[...document.querySelectorAll("#conversation-list .conversation-button")].find(b=>b.textContent==="旅程討論").click()');await until('selected.trip.conversationId==='+JSON.stringify(original)+' && activeProvider==="codex"');assert.equal(await js('document.getElementById("message").value'),'目前對話的草稿');
 await js('openSettings("ai")');await until('document.getElementById("settings-provider").value==="claude"');await js('document.getElementById("settings-provider").value="codex";document.getElementById("settings-provider").dispatchEvent(new Event("change"))');await until('document.getElementById("defaults-status").textContent==="已保存" && document.getElementById("defaults-effort").value==="high"');const beforeCodex=await js('selected.trip.conversationId');await js('closeSettings()');await until('!document.getElementById("conversation-new").disabled && !aiBusy');await js('document.getElementById("conversation-new").click()');await until('activeProvider==="codex" && selected.trip.conversationId!=='+JSON.stringify(beforeCodex)+' && selected.trip.featureState.effort==="high" && !aiBusy');assert.equal(await js('document.getElementById("chat-effort").value'),'high');
 await js('openSettings("projects")');assert.equal(await js('document.querySelector(".acquisition-card").contains(document.getElementById("choose-project")) && document.querySelector(".acquisition-card").contains(document.getElementById("open-project-github"))'),true);assert.equal(await js('document.getElementById("trip-details")'),null);await js('document.querySelector("#summary-trips details").open=true');await shot('project-light.png');await js('document.getElementById("open-project-github").click()');assert.equal(await js('document.getElementById("project-github-options").hidden'),false);
 await js('settingTab("tools")');await until('document.querySelectorAll("#environment-list .setting-row").length===3');assert.equal(await js('[...document.querySelectorAll("#environment-list .tool-title h3")].some(h=>h.textContent==="Gemini")'),false);assert.equal(await js('document.querySelector(".tool-title .tool-version").textContent'),'2.87.0');assert.equal(await js('[...document.querySelectorAll("#environment-list .setting-row")].find(r=>r.querySelector("h3").textContent==="Claude Code").querySelector(".status-pill").textContent'),'已找到');await shot('tools-light.png');
 await js('settingTab("backup")');assert.equal(await js('ui.setting'), 'sync');assert.equal(await js('document.getElementById("setting-backup").hidden'),false);await js('document.getElementById("sync-publish-tab").click()');assert.equal(await js('document.getElementById("setting-publish").hidden'),false);assert.equal(await js('document.getElementById("setting-backup").hidden'),true);await shot('sync-light.png');win.setSize(860,700);await js('settingTab("ai")');await shot('ai-narrow.png');assert.equal(await js('document.querySelector(".settings-content").scrollWidth<=document.querySelector(".settings-content").clientWidth'),true);
 await js('document.getElementById("defaults-effort").value="medium";document.getElementById("defaults-effort").dispatchEvent(new Event("change"))');await until('document.getElementById("defaults-status").textContent==="已保存" && document.getElementById("defaults-effort").value==="medium"');await js('document.getElementById("defaults-model").value="other-codex";document.getElementById("defaults-model").dispatchEvent(new Event("change"))');await until('document.getElementById("defaults-status").textContent==="已保存" && document.getElementById("defaults-effort").value==="low"');assert.deepEqual((await store.read()).state.aiDefaults,{provider:'codex',models:{claude:'other-claude',codex:'other-codex'},effort:'low'});
 win.destroy();await new Promise(r=>setTimeout(r,150));await store.setAIProvider('gemini');await store.setAIDefaults({provider:'gemini',models:{},effort:'medium'});
 const target={root:await fs.realpath(project),slug:'sample'},conversations=new ConversationStore(state);
 await conversations.update(target,s=>{s.provider='gemini';s.started=true;s.messages.push({role:'assistant',text:'保留下來的舊對話'});});
 win=await createWindow({...options,codexAccount:undefined});win.webContents.setBackgroundThrottling(false);
 await until('activeProvider==="gemini" && accountState.state==="paused" && !conversationLoading && realPreview?.status==="ready"');
 assert.equal(geminiConnections,0);assert.equal(await js('document.getElementById("send-message").disabled'),true);assert.equal(await js('document.getElementById("connect-from-chat").hidden'),true);
 assert.equal(await js('document.getElementById("messages").textContent.includes("保留下來的舊對話")'),true);assert.equal(await js('document.getElementById("chat-provider-locked").textContent'),'Gemini（暫停）');
 assert.equal((await js('window.travelDesktop.connectCodex()')).code,'PROVIDER_UNAVAILABLE');assert.equal((await js('window.travelDesktop.generateProposal({...conversationTarget(),text:"test"})')).code,'PROVIDER_UNAVAILABLE');assert.equal(geminiConnections,0);
 assert.equal((await js('window.travelDesktop.feature("provider-accounts")')).accounts.some(a=>a.id==='gemini'),false);
 console.log(JSON.stringify({passed:true,independentProviderLogin:true,defaultsDoNotSwitchChat:true,newConversationUsesDefaults:true,oldConversationRestoresProvider:true,legacyGeminiPaused:true,projectHierarchy:true,inlineBadgesAndVersions:true,mergedSyncTabs:true,visuals:['light','dark','narrow']}));
}).catch(async e=>{console.error(e);if(win&&!win.isDestroyed()){console.error(await js('JSON.stringify({notice:document.getElementById("notification").textContent,activeProvider,accountState})'));await shot('failure.png');}status=1;}).finally(async()=>{win?.destroy();try{await shutdown();}catch(error){console.error(error);status=1;}app.exit(status);});
