// Native renderer/IPC update integration; all release and installer actions are fake.
const {app}=require('electron');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const assert=require('node:assert/strict');const {EventEmitter}=require('node:events');
if(!process.env.TRAVEL_PLANNER_TEST_ROOT)throw Error('Run updater smoke through the native smoke runner');
const isolatedState=require('node:fs').realpathSync(process.env.TRAVEL_PLANNER_TEST_ROOT);process.env.TRAVEL_PLANNER_STATE_DIR=isolatedState;
const {createWindow,shutdown,isUpdateHandoff}=require('./main.cjs');const {UpdateManager}=require('./services/updater.cjs');
app.on('window-all-closed',()=>{});let win,state,timer,status=0,releaseEnvironment,releaseStop;const js=code=>win.webContents.executeJavaScript(code);
async function until(code){for(let i=0;i<200;i++){if(await js(code))return;await new Promise(r=>setTimeout(r,25));}throw Error('Update UI condition timed out: '+code);}
app.whenReady().then(async()=>{
  timer=setTimeout(()=>app.exit(1),40000);state=isolatedState;
  const envGate=new Promise(resolve=>{releaseEnvironment=resolve;});const stopGate=new Promise(resolve=>{releaseStop=resolve;});let stopCalls=0,installs=0,downloads=0,finishDownload,rejectInstall=true;
  const account=new EventEmitter();account.account={state:'disconnected'};account.stop=async()=>{stopCalls++;await stopGate;};
  const base='https://github.com/wangch15/travel-planner/releases/download/desktop-v9.0.0/';
  const release={state:'available',version:'9.0.0',currentVersion:'0.1.0',url:'https://github.com/wangch15/travel-planner/releases/tag/desktop-v9.0.0',assets:[{name:'latest-mac.yml',url:base+'latest-mac.yml',size:100},{name:'TravelPlanner-arm64.zip',url:base+'TravelPlanner-arm64.zip',size:1000}]};
  const native=new EventEmitter();native.checkForUpdates=async()=>({isUpdateAvailable:true,updateInfo:{version:'9.0.0',files:[{url:'TravelPlanner-arm64.zip',size:1000,sha512:Buffer.alloc(64,1).toString('base64')}]}});native.downloadUpdate=async()=>{downloads++;native.emit('download-progress',{percent:40});await new Promise(resolve=>{finishDownload=resolve;});return [];};native.quitAndInstall=()=>{assert.equal(isUpdateHandoff(),true);let prevented=false;win.emit('close',{preventDefault(){prevented=true;}});assert.equal(prevented,false);installs++;if(rejectInstall)native.emit('error',Error('fake signature rejection'));};native.setFeedURL=()=>{};
  win=await createWindow({stateDirectory:state,codexAccount:account,makeAuth:()=>({close:async()=>{},status:async()=>({connected:false})}),environmentService:{inspectEnvironment:async()=>{await envGate;return {tools:[]};},checkForUpdates:async()=>release},makeUpdater:options=>new UpdateManager({...options,platform:'darwin',detectCapability:async()=>({automatic:true,reason:null}),nativeFactory:()=>native})});
  win.webContents.setBackgroundThrottling(false);await until('document.readyState === "complete"');await js('document.getElementById("open-settings").click();document.querySelector("[data-setting=tools]").click();document.getElementById("check-updates").click()');
  await until('!document.getElementById("download-update").hidden');assert.equal(downloads,0);assert.equal(installs,0);assert.equal(native.autoDownload,false);assert.equal(native.autoInstallOnAppQuit,false);
  await js('document.getElementById("download-update").click()');await until('!document.getElementById("update-progress").hidden');assert.equal(downloads,1);assert.equal(await js('document.getElementById("update-progress").value'),40);assert.equal((await js('travelDesktop.feature("updates-install")')).ok,false);assert.equal(installs,0);
  finishDownload();await until('!document.getElementById("install-update").hidden && !document.getElementById("install-update").disabled');
  await js('void travelDesktop.feature("updates-install").then(result=>{window.updateInstallReply=result;})');await until('window.updateInstallReply?.scheduled === true');
  // An unrelated tracked request is still outstanding: reply must not wait on itself.
  assert.equal(installs,0);assert.equal(stopCalls,0);releaseEnvironment();for(let i=0;i<100&&!stopCalls;i++)await new Promise(r=>setTimeout(r,20));assert.ok(stopCalls>0);assert.equal(installs,0);releaseStop();for(let i=0;i<100&&!installs;i++)await new Promise(r=>setTimeout(r,20));assert.equal(installs,1);await until('document.getElementById("update-result").textContent.includes("更新未完成")');assert.equal((await js('travelDesktop.feature("updates-status")')).update.state,'error');assert.equal(isUpdateHandoff(),false);
  rejectInstall=false;await js('document.getElementById("check-updates").click()');await until('!document.getElementById("download-update").hidden');await js('document.getElementById("download-update").click()');for(let i=0;i<100&&downloads<2;i++)await new Promise(r=>setTimeout(r,20));finishDownload();await until('!document.getElementById("install-update").hidden && !document.getElementById("install-update").disabled');await js('document.getElementById("install-update").click()');for(let i=0;i<100&&installs<2;i++)await new Promise(r=>setTimeout(r,20));assert.equal(installs,2);
  console.log(JSON.stringify({passed:true,fakeReleaseOnly:true,explicitDownload:true,progress:true,installReplyBeforeDrain:true,drainedBeforeNativeInstall:true,failedInstallReopensApp:true}));
}).catch(e=>{console.error(e);status=1;}).finally(async()=>{clearTimeout(timer);releaseEnvironment?.();releaseStop?.();if(win&&!win.isDestroyed())win.destroy();try{await shutdown();}catch(error){console.error(error);status=1;}app.exit(status);});
