const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {AttachmentStore,fetchPublicReference}=require('../services/attachments.cjs');
async function fixture(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'attachments-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return {dir,store:new AttachmentStore(dir),target:{root:dir,slug:'sample-trip',accountKey:'account-1'}};}
test('copies text attachments and binds opaque IDs to account/trip',async t=>{const {dir,store,target}=await fixture(t);const file=path.join(dir,'notes.md');await fs.writeFile(file,'# Holidays\nSlow travel');const a=await store.add(target,file);assert.equal(a.kind,'text');await fs.writeFile(file,'changed');assert.equal((await store.read(target,a.id)).text,'# Holidays\nSlow travel');assert.equal((await store.list(target)).length,1);await assert.rejects(store.read({...target,accountKey:'other'},a.id));await assert.rejects(store.read(target,'../x'));assert.equal(await store.remove(target,a.id),true);assert.deepEqual(await store.list(target),[]);});
test('rejects unsupported, binary, oversized, symlink and malformed images',async t=>{const {dir,store,target}=await fixture(t);for(const [name,data] of [['x.pdf','%PDF-1.7'],['x.txt',Buffer.from([255,0,254])],['x.png','not png'],['x.md',Buffer.alloc(1024*1024+1,65)]]){const f=path.join(dir,name);await fs.writeFile(f,data);await assert.rejects(store.add(target,f));}await fs.writeFile(path.join(dir,'plain.txt'),'hello');await fs.symlink('plain.txt',path.join(dir,'link.txt'));await assert.rejects(store.add(target,path.join(dir,'link.txt')));});
test('accepts small PNG with inspected dimensions, preserves bytes and reports no OCR',async t=>{const {dir,store,target}=await fixture(t);const bytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l6UAAAAASUVORK5CYII=','base64');const file=path.join(dir,'one.png');await fs.writeFile(file,bytes);const added=await store.add(target,file);assert.equal(added.width,1);assert.equal(added.mime,'image/png');const full=await store.read(target,added.id);assert.equal(full.text,undefined);assert.deepEqual(await fs.readFile(full.imagePath),bytes);});
test('reference fetch pins public resolution, strips scripts and records exact URL/date',async()=>{let seen;const ref=await fetchPublicReference('https://example.com/info',{resolve:async()=>['93.184.216.34'],request:async(url,opts)=>{seen=opts.address;return {statusCode:200,headers:{'content-type':'text/html'},body:Buffer.from('<title>Visit</title><script>secret()</script><p>Open &amp; welcoming</p>')};}});assert.equal(seen,'93.184.216.34');assert.equal(ref.url,'https://example.com/info');assert.match(ref.text,/Open & welcoming/);assert.doesNotMatch(ref.text,/secret/);assert.ok(ref.checkedAt);});
test('reference rejects private addresses, redirect SSRF, credentials and excess data',async()=>{for(const url of ['http://127.0.0.1','http://[::1]','http://user:pass@example.com','file:///etc/passwd'])await assert.rejects(fetchPublicReference(url));await assert.rejects(fetchPublicReference('https://example.com',{resolve:async()=>['10.0.0.1'],request:async()=>{throw Error('must not request');}}));let calls=0;await assert.rejects(fetchPublicReference('https://example.com',{resolve:async()=>['93.184.216.34'],request:async()=>{calls++;return {statusCode:302,headers:{location:'http://169.254.169.254'},body:Buffer.alloc(0)};}}));assert.equal(calls,1);await assert.rejects(fetchPublicReference('https://example.com',{resolve:async()=>['93.184.216.34'],request:async()=>({statusCode:200,headers:{'content-type':'text/plain'},body:Buffer.alloc(2*1024*1024+1)})}));});
test('stored file changes and link replacement fail closed',async t=>{const {dir,store,target}=await fixture(t);const file=path.join(dir,'notes.txt');await fs.writeFile(file,'hello');const item=await store.add(target,file);const scope=store.scope(target);await fs.writeFile(path.join(scope,item.id+'.bin'),'other');await assert.rejects(store.read(target,item.id),{code:'ATTACHMENT_CHANGED'});await fs.rm(path.join(scope,item.id+'.bin'));await fs.symlink(file,path.join(scope,item.id+'.bin'));await assert.rejects(store.read(target,item.id),{code:'UNSAFE_ATTACHMENT'});});
test('reference DNS timeout is bounded and does not issue a request',async()=>{let calls=0;await assert.rejects(fetchPublicReference('https://example.com',{timeoutMs:5,resolve:()=>new Promise(()=>{}),request:async()=>{calls++;}}),{code:'REFERENCE_TIMEOUT'});assert.equal(calls,0);});
