const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {createHash}=require('node:crypto');
const {ToolSupport,prepareToolEnvironment,downloadAccept,extractDefault}=require('../services/tool-support.cjs');
async function fixture(t,options={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'tool-support-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const terminal=[];const service=new ToolSupport(root,{platform:'darwin',arch:'arm64',home:path.join(root,'home'),env:{PATH:'/usr/bin:/bin'},run:async command=>{if(command===process.execPath)return {stdout:'4.135.0'};throw Error('missing');},openTerminal:async value=>{terminal.push(value);},...options});return {root,service,terminal};}
test('only allowlisted install plans run, require explicit confirmation, and terminal launch is not reported installed',async t=>{const {service,terminal}=await fixture(t);await assert.rejects(service.prepare('gh; rm -rf /'));const plan=await service.prepare('gemini');assert.equal(plan.method,'terminal');assert.match(plan.commandPreview,/@google\/gemini-cli/);await assert.rejects(service.install(plan.token),{code:'TOOL_CONFIRMATION_REQUIRED'});assert.equal(terminal.length,0);const result=await service.install(plan.token,{confirmed:true});assert.equal(result.state,'terminal-opened');assert.equal(result.installed,false);assert.equal(terminal.length,1);await assert.rejects(service.install(plan.token,{confirmed:true}),{code:'INSTALL_PLAN_EXPIRED'});});
test('bundled Wrangler needs no installer, and provider recipes install into app-owned prefix without a stale version',async t=>{const {service,terminal}=await fixture(t);const w=await service.prepare('wrangler');assert.equal(w.method,'bundled');assert.equal((await service.install(w.token,{confirmed:true})).state,'ready');assert.equal(terminal.length,0);const codex=await service.prepare('codex');assert.match(codex.commandPreview,/@openai\/codex\b/);assert.doesNotMatch(codex.commandPreview,/@openai\/codex@\d/);assert.match(codex.commandPreview,/--prefix/);assert.doesNotMatch(codex.commandPreview,/npm install -g/);const gemini=await service.prepare('gemini');assert.match(gemini.commandPreview,/@google\/gemini-cli@0\.46\.0/);});
function downloads(corrupt=false,platform='darwin'){const bytes=Buffer.from('official archive fixture'),digest=createHash('sha256').update(bytes).digest('hex');const tag='v2.101.0',base='https://github.com/cli/cli/releases/download/'+tag+'/',name=platform==='win32'?'gh_2.101.0_windows_arm64.zip':'gh_2.101.0_macOS_arm64.zip',checksums='gh_2.101.0_checksums.txt';return async url=>{if(url.includes('/releases/latest'))return Buffer.from(JSON.stringify({tag_name:tag,draft:false,prerelease:false,assets:[{name,browser_download_url:base+name,size:bytes.length},{name:checksums,browser_download_url:base+checksums,size:100}]}));if(url.endsWith('_checksums.txt'))return Buffer.from(digest+'  '+name+'\n');return corrupt?Buffer.from('bad bytes'):bytes;};}
test('managed GH install verifies checksum/version, preserves global tools and becomes available through app PATH',async t=>{let extracts=0;const platform=process.platform==='win32'?'win32':'darwin',binary=platform==='win32'?'gh.exe':'gh';const {service,root}=await fixture(t,{platform,env:{PATH:''},download:downloads(false,platform),extract:async(_archive,destination)=>{extracts++;const folder=platform==='win32'?path.join(destination,'bin'):path.join(destination,'gh_2.101.0_macOS_arm64/bin');await fs.mkdir(folder,{recursive:true});await fs.writeFile(path.join(folder,binary),'fixture binary');},run:async command=>{if(path.basename(command)===binary)return {stdout:'gh version 2.101.0 (2026-09-23)'};throw Error('missing');}});const plan=await service.prepare('gh');const installed=await service.install(plan.token,{confirmed:true});assert.equal(installed.state,'installed');assert.equal(extracts,1);const resolved=await service.resolveCommand('gh');assert.ok(resolved.command.startsWith(root));assert.equal(resolved.source,'managed');const environment=await service.environment();assert.ok(environment.PATH.split(platform==='win32'?';':':').includes(path.dirname(resolved.command)));assert.equal((await service.inspect()).tools.find(t=>t.id==='gh').status,'ready');});
test('checksum mismatch never extracts or claims installation',async t=>{const {service}=await fixture(t,{download:downloads(true),extract:async()=>{throw Error('must not extract');}});const p=await service.prepare('gh');await assert.rejects(service.install(p.token,{confirmed:true}),{code:'TOOL_CHECKSUM_MISMATCH'});assert.equal((await service.inspect()).tools.find(t=>t.id==='gh').status,'missing');});
test('managed directories refuse symlinks and applying environment only prepends discovered directories',async t=>{const {root,service}=await fixture(t);await fs.mkdir(path.join(root,'elsewhere'));await fs.symlink('elsewhere',path.join(root,'tools'),process.platform==='win32'?'junction':'dir');await assert.rejects(service.prepare('codex'),{code:'UNSAFE_TOOL_DIRECTORY'});const other=await fs.mkdtemp(path.join(os.tmpdir(),'tool-env-'));t.after(()=>fs.rm(other,{recursive:true,force:true}));const systemDirectory=path.join(other,'system-bin');await fs.mkdir(systemDirectory);const env={PATH:systemDirectory},platform=process.platform==='win32'?'win32':'darwin';await prepareToolEnvironment(other,{platform,env,home:path.join(other,'home')});assert.ok(env.PATH.split(platform==='win32'?';':':').includes(systemDirectory));});
test('Windows Git installs in the background with WinGet and never includes renderer commands',async t=>{const calls=[];const {service,terminal}=await fixture(t,{platform:'win32',arch:'x64',run:async(command,args=[])=>{calls.push({command,args});if(command==='winget.exe')return {stdout:''};if(command==='git')return {stdout:'git version 2.51.0'};if(command===process.execPath)return {stdout:'4.135.0'};throw Error('missing');}});service.resolveCommand=async id=>id==='git'?{command:'git',args:[],env:{},source:'system'}:null;const git=await service.prepare('git');assert.equal(git.method,'background-winget');const result=await service.install(git.token,{confirmed:true,command:'evil'});assert.equal(result.state,'installed');assert.equal(terminal.length,0);const winget=calls.find(c=>c.command==='winget.exe');assert.deepEqual(winget.args.slice(0,6),['install','--id','Git.Git','--exact','--source','winget']);assert.ok(!JSON.stringify(calls).includes('evil'));});

test('Mac Git asks macOS to show the Apple installer and is not reported installed until detected',async t=>{const calls=[];const {service,terminal}=await fixture(t,{run:async(command,args=[])=>{calls.push({command,args});if(command===process.execPath)return {stdout:'4.135.0'};return {stdout:''};}});const plan=await service.prepare('git');assert.equal(plan.method,'system-dialog');const result=await service.install(plan.token,{confirmed:true});assert.equal(result.state,'dialog-opened');assert.equal(result.installed,false);assert.equal(terminal.length,0);assert.deepEqual(calls.find(c=>c.command==='/usr/bin/xcode-select').args,['--install']);});

test('Claude installs with the official script in the background and must be detected afterwards',async t=>{const calls=[];let installed=false;const {service,terminal}=await fixture(t,{run:async(command,args=[])=>{calls.push({command,args});if(command==='/bin/bash'){installed=true;return {stdout:''};}if(command==='claude'&&installed)return {stdout:'2.1.281 (Claude Code)'};if(command===process.execPath)return {stdout:'4.135.0'};throw Error('missing');}});service.resolveCommand=async id=>id==='claude'&&installed?{command:'claude',args:[],env:{},source:'system'}:null;const plan=await service.prepare('claude');assert.equal(plan.method,'background-script');assert.match(plan.commandPreview,/https:\/\/claude\.ai\/install\.sh/);const result=await service.install(plan.token,{confirmed:true});assert.equal(result.state,'installed');assert.equal(terminal.length,0);assert.match(calls.find(c=>c.command==='/bin/bash').args[1],/curl -fsSL https:\/\/claude\.ai\/install\.sh \| \/bin\/bash/);
  installed=false;const again=await service.prepare('claude');service.run=async()=>({stdout:''});await assert.rejects(service.install(again.token,{confirmed:true}),{code:'TOOL_INSTALL_UNVERIFIED'});});
test('Codex and Claude commands remain detectable when --version is unavailable or changes format',async t=>{
 const {service}=await fixture(t,{run:async command=>{if(command==='claude')throw Error('changed version flag');return {stdout:'Codex nightly build'};}});
 service.resolveCommand=async id=>['codex','claude'].includes(id)?{command:id,args:[],env:{},source:'system'}:null;
 const tools=(await service.inspect()).tools;
 for(const id of ['codex','claude']){const item=tools.find(tool=>tool.id===id);assert.equal(item.status,'ready');assert.equal(item.version,null);assert.equal(item.requiredVersion,null);}
});
test('installed Codex and Claude versions are diagnostic only, while legacy Gemini remains guarded',async t=>{const outputs={claude:'2.1.280 (Claude Code)',gemini:'0.60.0',codex:'codex-cli 0.156.3',node:'v24.16.0',git:'git version 2.50.0',gh:'gh version 2.100.0',wrangler:'4.135.0'};const {service}=await fixture(t,{run:async command=>({stdout:outputs[command]})});service.resolveCommand=async id=>({command:id,args:[],env:{},source:'system'});const tools=(await service.inspect()).tools;assert.equal(tools.find(t=>t.id==='claude').requiredVersion,null);assert.equal(tools.find(t=>t.id==='claude').status,'ready');assert.equal(tools.find(t=>t.id==='codex').version,'0.156.3');assert.equal(tools.find(t=>t.id==='codex').requiredVersion,null);assert.equal(tools.find(t=>t.id==='gemini').requiredVersion,'0.46.0');assert.equal(tools.find(t=>t.id==='gemini').status,'unsupported');assert.equal(tools.find(t=>t.id==='codex').status,'ready');});
// Follow the host platform: path.join and absolute paths must match the simulated OS.
const NODE_PLATFORM=process.platform==='win32'?'win32':'darwin';
const NODE_NAME=NODE_PLATFORM==='win32'?'node-v24.9.0-win-arm64.zip':'node-v24.9.0-darwin-arm64.tar.gz';
const NODE_DIR=path.join('tools/node','24.9.0-'+NODE_PLATFORM+'-arm64');
const NODE_BIN=NODE_PLATFORM==='win32'?NODE_DIR:path.join(NODE_DIR,'bin');
const NODE_EXE=NODE_PLATFORM==='win32'?'node.exe':'node';
const NPM_CLI=path.join(NODE_DIR,NODE_PLATFORM==='win32'?'node_modules/npm/bin/npm-cli.js':'lib/node_modules/npm/bin/npm-cli.js');
const CODEX_SCRIPT=path.join('tools/npm/node_modules/@openai/codex/bin/codex.js');
function nodeDownloads(corrupt=false){const bytes=Buffer.from('official node archive'),digest=createHash('sha256').update(bytes).digest('hex');const seen=[];const fn=async url=>{seen.push(url);if(url==='https://nodejs.org/dist/latest-v24.x/SHASUMS256.txt')return Buffer.from('0000  node-v24.9.0-darwin-x64.tar.gz\n0000  node-v24.9.0-win-x64.zip\n'+digest+'  '+NODE_NAME+'\n');if(url==='https://nodejs.org/dist/v24.9.0/'+NODE_NAME)return corrupt?Buffer.from('tampered'):bytes;throw Error('unexpected '+url);};fn.seen=seen;return fn;}
function nodeFixture(root,calls){const delimiter=NODE_PLATFORM==='win32'?';':':';return {platform:NODE_PLATFORM,arch:'arm64',env:{PATH:NODE_PLATFORM==='win32'?'':'/usr/bin:/bin'},
  extract:async(_archive,destination)=>{const base=path.join(destination,NODE_NAME.replace(/\.(tar\.gz|zip)$/,''));const bin=NODE_PLATFORM==='win32'?base:path.join(base,'bin');await fs.mkdir(bin,{recursive:true});await fs.writeFile(path.join(bin,NODE_EXE),'node-binary');const cli=path.join(base,NODE_PLATFORM==='win32'?'node_modules/npm/bin':'lib/node_modules/npm/bin');await fs.mkdir(cli,{recursive:true});await fs.writeFile(path.join(cli,'npm-cli.js'),'cli');},
  run:async(command,args=[],options={})=>{calls.push({command,args,options});if(command===process.execPath)return {stdout:'4.135.0'};const isNode=command.endsWith(path.join(NODE_PLATFORM==='win32'?'':'bin',NODE_EXE));
    if(isNode&&args[0]==='--version')return {stdout:'v24.9.0'};
    if(isNode&&args.includes('install')){if(NODE_PLATFORM==='win32'){const script=path.join(root,CODEX_SCRIPT);await fs.mkdir(path.dirname(script),{recursive:true});await fs.writeFile(script,'// codex');}else{const bin=path.join(root,'tools/npm/node_modules/.bin');await fs.mkdir(bin,{recursive:true});await fs.writeFile(path.join(bin,'codex'),'#!/usr/bin/env node');}return {stdout:'added 2 packages'};}
    if(command.endsWith(path.join('.bin','codex'))||isNode&&args[0]===path.join(root,CODEX_SCRIPT))return {stdout:'codex-cli 0.156.1'};
    throw Object.assign(Error('missing'),{code:'ENOENT'});},delimiter};}

test('Codex installs in the background with an App-downloaded, checksum-verified Node.js — no Homebrew or terminal',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'tool-node-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const calls=[],terminal=[];const download=nodeDownloads();
  const {delimiter,...options}=nodeFixture(root,calls);
  const service=new ToolSupport(root,{...options,home:path.join(root,'home'),download,openTerminal:async v=>{terminal.push(v);}});service.systemNode=async()=>null;
  const plan=await service.prepare('codex');
  assert.equal(plan.method,'managed-npm');assert.doesNotMatch(plan.commandPreview+plan.steps.join(''),/brew|Homebrew|sudo/);assert.match(plan.commandPreview,/@openai\/codex\b/);
  const result=await service.install(plan.token,{confirmed:true});
  assert.equal(result.state,'installed');assert.equal(result.toolStatus.status,'ready');assert.equal(terminal.length,0);
  const install=calls.find(c=>c.args.includes('install'));
  assert.equal(install.args[0],path.join(root,NPM_CLI));
  assert.ok(install.args.includes('@openai/codex'));assert.ok(install.args.includes('--prefix'));assert.equal(install.options.cwd,path.join(root,'tools/npm'));
  assert.ok(install.options.env.PATH.startsWith(path.join(root,NODE_BIN)));
  assert.deepEqual(download.seen,['https://nodejs.org/dist/latest-v24.x/SHASUMS256.txt','https://nodejs.org/dist/v24.9.0/'+NODE_NAME]);
  assert.ok((await service.environment()).PATH.split(delimiter).includes(path.join(root,NODE_BIN)));
  const node=(await service.prepare('node'));assert.equal(node.method,'managed-node');
});

test('a tampered Node.js download is never extracted, and Codex is not reported installed',async t=>{
  const root=await fs.mkdtemp(path.join(os.tmpdir(),'tool-node-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const calls=[];
  const {delimiter:_d,...options}=nodeFixture(root,calls);const service=new ToolSupport(root,{...options,home:path.join(root,'home'),download:nodeDownloads(true),extract:async()=>{throw Error('must not extract');}});service.systemNode=async()=>null;
  const plan=await service.prepare('codex');
  await assert.rejects(service.install(plan.token,{confirmed:true}),{code:'TOOL_CHECKSUM_MISMATCH'});
  assert.equal(calls.some(c=>c.args.includes('install')),false);
});
test('Windows finds Codex and Claude that npm -g installed next to node.exe (nvm-windows), not only under %APPDATA%\npm',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'tool-support-npm-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const prefix=path.join(root,'nvm','nodejs'),other=path.join(root,'other'),bin=path.join(prefix,'node_modules/@openai/codex/node_modules/@openai/codex-win32-x64/vendor/x86_64-pc-windows-msvc/bin'),cli=path.join(prefix,'node_modules/@anthropic-ai/claude-code/cli.js');
 await fs.mkdir(bin,{recursive:true});await fs.mkdir(path.dirname(cli),{recursive:true});await fs.mkdir(path.join(other,'node_modules'),{recursive:true});
 for(const file of [path.join(prefix,'codex.cmd'),path.join(prefix,'claude.cmd'),path.join(prefix,'node.exe'),path.join(bin,'codex.exe'),cli])await fs.writeFile(file,'');
 const service=new ToolSupport(path.join(root,'state'),{platform:'win32',arch:'x64',home:path.join(root,'home'),env:{PATH:[other,prefix].join(';'),APPDATA:path.join(root,'appdata')}});
 assert.deepEqual(await service.npmGlobalRoots(),[path.join(root,'appdata','npm/node_modules'),path.join(prefix,'node_modules')],'a PATH folder without an npm tool shim is not an npm root');
 assert.ok((await service.environment()).PATH.split(';').includes(bin));
 assert.deepEqual(await service.resolveCommand('claude'),{command:path.join(prefix,'node.exe'),args:[cli],env:await service.environment(),source:'system'});
});
test('GitHub release metadata is requested as JSON; downloads stay binary',()=>{
 assert.equal(downloadAccept(new URL('https://api.github.com/repos/cli/cli/releases/latest')),'application/vnd.github+json');
 for(const url of ['https://github.com/cli/cli/releases/download/v2.0.0/gh.zip','https://nodejs.org/dist/latest-v24.x/SHASUMS256.txt'])assert.equal(downloadAccept(new URL(url)),'application/octet-stream');
});
test('Windows extracts with the system tar, not a Git-bundled GNU tar that happens to be first on PATH',async()=>{
 const commands=[];await extractDefault('archive.zip','out',{platform:'win32',systemRoot:'C:\Windows',run:async command=>{commands.push(command);return {stdout:'node-v24.0.0-win-x64/\nnode-v24.0.0-win-x64/node.exe\n'};}});
 assert.deepEqual(commands,[path.join('C:\Windows','System32','tar.exe'),path.join('C:\Windows','System32','tar.exe')]);
});

test('an existing Claude is updated in place with its own official updater, then verified',async t=>{const calls=[];let version='2.1.40';const {service,terminal}=await fixture(t,{run:async(command,args=[])=>{calls.push({command,args});if(command==='/opt/claude'&&args[0]==='update'){version='2.1.282';return {stdout:''};}if(command==='/opt/claude')return {stdout:version+' (Claude Code)'};if(command===process.execPath)return {stdout:'4.135.0'};throw Error('missing');}});service.resolveCommand=async id=>id==='claude'?{command:'/opt/claude',args:[],env:{PATH:'/usr/bin'},source:'system'}:null;
  const plan=await service.prepare('claude');assert.equal(plan.method,'background-update');assert.equal(plan.commandPreview,'claude update');
  const result=await service.install(plan.token,{confirmed:true});assert.equal(result.state,'updated');assert.equal(result.toolStatus.version,'2.1.282');assert.equal(terminal.length,0);assert.equal(calls.some(c=>c.command==='/bin/bash'),false,'a working updater does not re-run the installer');});
test('when Claude cannot update itself, the official installer runs instead',async t=>{const calls=[];const {service}=await fixture(t,{run:async(command,args=[])=>{calls.push({command,args});if(command==='/opt/claude'&&args[0]==='update')throw Object.assign(Error('update failed'),{code:1});if(command==='/opt/claude')return {stdout:'2.1.282 (Claude Code)'};if(command==='/bin/bash')return {stdout:''};if(command===process.execPath)return {stdout:'4.135.0'};throw Error('missing');}});service.resolveCommand=async id=>id==='claude'?{command:'/opt/claude',args:[],env:{},source:'system'}:null;
  const plan=await service.prepare('claude');const result=await service.install(plan.token,{confirmed:true});assert.equal(result.state,'updated');assert.match(calls.find(c=>c.command==='/bin/bash').args[1],/claude\.ai\/install\.sh/);});
